//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhoneViewController.h"

#import "DialerViewDelegate.h"
#import "TPDialerKeypadDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class CNContactStore, NSString, NSTimer, PHAbstractDialerView, TUCallProviderManager, TUContactsDataProvider;

@interface DialerController : PhoneViewController <UIGestureRecognizerDelegate, DialerViewDelegate, TPDialerKeypadDelegate>
{
    PHAbstractDialerView *_dialerView;
    NSTimer *_deleteTimer;
    NSTimer *_lookupTimer;
    unsigned int _calledNumber:1;
    unsigned int _didDeleteRepeat:1;
    unsigned int _dtmfPlaying;
    _Bool _shouldHideDeleteButtonWhenEmpty;
    _Bool _loadedLastDialedNumberCache;
    _Bool _wantsCallButtonAnimation;
    int _dialerType;
    TUCallProviderManager *_callProviderManager;
    NSString *_lastDialedNumberCache;
    NSString *_phoneNumberPrefixHint;
    long long _backgroundStyle;
    CNContactStore *_contactStore;
    TUContactsDataProvider *_contactsDataProvider;
}

+ (id)defaultPNGName;
+ (_Bool)launchFieldTestIfNeeded:(id)arg1;
+ (void)playDTMFToneForKey:(unsigned char)arg1;
+ (_Bool)shouldStringAutoDial:(id)arg1 givenLastChar:(BOOL)arg2;
+ (id)tabBarIconImage;
+ (id)tabBarIconImageName;
+ (id)tabBarIconName;
+ (int)tabViewType;
- (void).cxx_destruct;
- (void)_addButtonClicked:(id)arg1;
- (void)_animateCallButton;
- (void)_applicationWillResignActiveNotification:(id)arg1;
- (void)_callButtonPressed:(id)arg1;
- (void)_callButtonPressedActionWithCallProvider:(id)arg1;
- (void)_callStatusChanged:(id)arg1;
- (void)_clearDisplayIfNecessary;
- (void)_deleteButtonClicked:(id)arg1;
- (void)_deleteButtonDown:(id)arg1;
- (void)_deleteRepeat;
- (void)_dialVoicemail;
- (void)_dialWithRequest:(id)arg1;
- (_Bool)_disableAutomaticKeyboardUI;
- (void)_fadeSubviewsOf:(id)arg1 excludingViews:(id)arg2 toValue:(double)arg3;
- (void)_handleSIMInsertionOrRemoval;
- (void)_phonePad:(id)arg1 appendString:(id)arg2 suppressClearingDialedNumber:(_Bool)arg3;
- (id)_qualifyNumberIfNecessary:(id)arg1;
- (void)_resetButtonAnimation;
- (void)_startDeleteTimer;
- (void)_statusBarHeightChanged:(id)arg1;
- (void)_stopDeleteTimer;
- (void)_stopLookupTimer;
- (void)_updateCallButtonEnabledState:(id)arg1;
- (void)_updateCallButtonEnabledState:(id)arg1 updateNameNow:(_Bool)arg2;
- (void)_updateLCDNameLabelWithAMatchingName:(_Bool)arg1;
- (void)_updateLCDNameLabelWithOriginallyPastedString:(id)arg1;
- (void)_updateName;
- (void)applicationDidResume;
@property(nonatomic) long long backgroundStyle; // @synthesize backgroundStyle=_backgroundStyle;
@property(retain, nonatomic) TUCallProviderManager *callProviderManager; // @synthesize callProviderManager=_callProviderManager;
- (id)contactResultForPhoneNumber:(id)arg1;
@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(retain, nonatomic) TUContactsDataProvider *contactsDataProvider; // @synthesize contactsDataProvider=_contactsDataProvider;
- (void)deactivateAudioServices;
- (void)dealloc;
- (_Bool)defaultActionIsFaceTimeAudio;
- (id)defaultCallProvider;
@property int dialerType; // @synthesize dialerType=_dialerType;
@property(readonly) PHAbstractDialerView *dialerView; // @synthesize dialerView=_dialerView;
- (void)dialerView:(id)arg1 stringWasPasted:(id)arg2;
- (void)dialerViewTextDidChange:(id)arg1;
- (_Bool)digitsEntered;
- (void)handleApplicationDidEnterBackgroundNotification:(id)arg1;
- (void)handleApplicationWillEnterForegroundNotification:(id)arg1;
- (void)handleSwipeGesture:(id)arg1;
- (id)initWithDialerType:(int)arg1;
- (id)initWithDialerType:(int)arg1 contactStore:(id)arg2;
- (_Bool)isShowingDoubleHeightStatusBar;
@property(copy, nonatomic) NSString *lastDialedNumber;
@property(retain) NSString *lastDialedNumberCache; // @synthesize lastDialedNumberCache=_lastDialedNumberCache;
- (void)loadView;
@property _Bool loadedLastDialedNumberCache; // @synthesize loadedLastDialedNumberCache=_loadedLastDialedNumberCache;
- (void)performCallActionForCallProvider:(id)arg1;
- (void)performCallActionForCallProvider:(id)arg1 video:(_Bool)arg2;
- (void)performCharacterAddAction:(id)arg1;
- (void)performDeleteAction;
@property(copy, nonatomic) NSString *phoneNumberPrefixHint; // @synthesize phoneNumberPrefixHint=_phoneNumberPrefixHint;
- (void)phonePad:(id)arg1 appendString:(id)arg2;
- (void)phonePad:(id)arg1 appendString:(id)arg2 playDTMFTone:(_Bool)arg3;
- (void)phonePad:(id)arg1 dialerCharacterButtonWasHeld:(unsigned int)arg2;
- (void)phonePad:(id)arg1 keyDown:(BOOL)arg2;
- (void)phonePad:(id)arg1 keyUp:(BOOL)arg2;
- (void)phonePad:(id)arg1 replaceLastDigitWithString:(id)arg2;
- (void)phonePadDeleteLastDigit:(id)arg1;
- (void)phonePadDidEndSounds:(id)arg1;
- (void)prepareForSnapshot;
- (id)pseudoNameStringForDestinationID:(id)arg1;
- (_Bool)requestAudioServicesActivate;
- (void)restoreLastDialedNumber;
- (void)setAudioServicesActivated:(_Bool)arg1;
- (void)setBackgroundStyle:(long long)arg1 animated:(_Bool)arg2;
@property(nonatomic) _Bool shouldHideDeleteButtonWhenEmpty; // @synthesize shouldHideDeleteButtonWhenEmpty=_shouldHideDeleteButtonWhenEmpty;
@property(nonatomic) _Bool wantsCallButtonAnimation; // @synthesize wantsCallButtonAnimation=_wantsCallButtonAnimation;
- (_Bool)shouldAnimateCallButton;
- (_Bool)shouldSnapshot;
- (void)showOrHideDeleteButton;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

