//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhoneApplication.h"

@interface MobilePhoneApplication : PhoneApplication
{
}

- (_Bool)_isIPad;
- (_Bool)alwaysShowLocalVideo;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (_Bool)audioButtonAllowsPhoneCallsAndFaceTimeAudio;
- (_Bool)badgesMissedFaceTimeAudio;
- (_Bool)badgesMissedFaceTimeVideo;
- (_Bool)badgesMissedTelephonyCalls;
- (_Bool)contentViewCanRotate;
- (void)dealloc;
- (int)defaultAction;
- (_Bool)hasEnhancedVoicemail;
- (long long)headerViewNumberOfCallsToShow;
- (_Bool)headerViewShowsAllRecentCalls;
- (id)init;
- (void)refreshDynamicApplicationShortcuts;
- (id)rootViewController;
- (_Bool)shouldHideVoicemailUI;
- (_Bool)showSplashScreenOnSignin;
- (_Bool)showsFaceTimeAudio;
- (_Bool)showsFaceTimeAudioFavorites;
- (_Bool)showsFaceTimeAudioRecents;
- (_Bool)showsFaceTimeVideo;
- (_Bool)showsFaceTimeVideoFavorites;
- (_Bool)showsFaceTimeVideoRecents;
- (_Bool)showsPhoneDialer;
- (_Bool)showsPhoneVoicemail;
- (_Bool)showsTelephonyCalls;
- (_Bool)showsTelephonyFavorites;
- (_Bool)showsTelephonyRecents;
- (_Bool)showsThirdPartyRecents;
- (_Bool)tabBarCanSlide;
- (_Bool)tabBarFillsScreen;
- (unsigned int)userInterfaceStyle;
- (_Bool)usesBlendModes;

@end

