//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHTableViewController.h"

#import "CNContactPickerDelegate.h"
#import "CNUIFavoritesEntryPickerDelegate.h"
#import "CNUIObjectViewControllerDelegate.h"
#import "PHTabBarSystemItemProtocol.h"

@class CNAvatarViewControllerSettings, CNContactPickerViewController, CNUIFavoritesEntryPicker, NSArray, NSCache, NSString, TPFavoritesController, UIBarButtonItem;

@interface MPFavoritesTableViewController : PHTableViewController <CNContactPickerDelegate, CNUIFavoritesEntryPickerDelegate, CNUIObjectViewControllerDelegate, PHTabBarSystemItemProtocol>
{
    _Bool _shouldShowAddButtonItem;
    CNAvatarViewControllerSettings *_avatarViewControllerSettings;
    TPFavoritesController *_favoritesController;
    NSCache *_contactCache;
    NSArray *_favoritesEntries;
    UIBarButtonItem *_addButtonItem;
    CNContactPickerViewController *_contactPickerViewController;
    CNUIFavoritesEntryPicker *_favoritesEntryPicker;
}

+ (CDStruct_5ec447a9)badge;
+ (id)defaultPNGName;
+ (id)moveObjectAtIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2 inArray:(id)arg3;
+ (id)tabBarIconName;
+ (int)tabViewType;
- (void).cxx_destruct;
- (void)addButtonAction:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *addButtonItem; // @synthesize addButtonItem=_addButtonItem;
@property(retain, nonatomic) CNAvatarViewControllerSettings *avatarViewControllerSettings; // @synthesize avatarViewControllerSettings=_avatarViewControllerSettings;
- (void)commonInit;
@property(readonly, nonatomic) NSCache *contactCache; // @synthesize contactCache=_contactCache;
- (id)contactCacheKeyForFavoritesEntry:(id)arg1;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
@property(retain, nonatomic) CNContactPickerViewController *contactPickerViewController; // @synthesize contactPickerViewController=_contactPickerViewController;
- (void)dealloc;
@property(readonly, nonatomic) TPFavoritesController *favoritesController; // @synthesize favoritesController=_favoritesController;
@property(copy, nonatomic) NSArray *favoritesEntries; // @synthesize favoritesEntries=_favoritesEntries;
- (id)favoritesEntryAtIndex:(long long)arg1;
@property(retain, nonatomic) CNUIFavoritesEntryPicker *favoritesEntryPicker; // @synthesize favoritesEntryPicker=_favoritesEntryPicker;
- (void)favoritesEntryPicker:(id)arg1 didPickEntry:(id)arg2;
- (id)favoritesEntryPickerContactForContact:(id)arg1 contactStore:(id)arg2;
- (void)handleTPFavoritesControllerFavoritesEntriesDidChangeNotification:(id)arg1;
- (void)handleUIContentSizeCategoryDidChangeNotification:(id)arg1;
- (id)hostingViewControllerForController:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFavoritesController:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (id)initWithStyle:(long long)arg1 favoritesController:(id)arg2;
- (void)makeUIForDefaultPNG;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)prepareForSnapshot;
- (void)refreshView;
- (void)reloadDataIfNeeded;
- (void)reloadDataSource;
- (void)removeFavoriteEntryAtIndexPath:(id)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setNavigationItemsForEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) _Bool shouldShowAddButtonItem; // @synthesize shouldShowAddButtonItem=_shouldShowAddButtonItem;
- (void)setShouldShowAddButtonItem:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)shouldSnapshot;
- (long long)tabBarSystemItem;
- (unsigned long long)tabBarSystemItemTag;
- (id)tabBarSystemItemTitle;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 prefetchRowsAtIndexPaths:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

