//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPVoicemailTableHeaderView.h"

@class NSLayoutConstraint, UIButton;

@interface MPVoicemailConnectionUnavailableView : MPVoicemailTableHeaderView
{
    UIButton *_button;
    NSLayoutConstraint *_buttonCenterXLayoutConstraint;
    NSLayoutConstraint *_buttonLeadingLayoutConstraint;
    NSLayoutConstraint *_buttonTrailingLayoutConstraint;
    NSLayoutConstraint *_buttonTitleLabelFirstBaselineLayoutConstraint;
    NSLayoutConstraint *_buttonTitleLabelLastBaselineLayoutConstraint;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) NSLayoutConstraint *buttonCenterXLayoutConstraint; // @synthesize buttonCenterXLayoutConstraint=_buttonCenterXLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *buttonLeadingLayoutConstraint; // @synthesize buttonLeadingLayoutConstraint=_buttonLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *buttonTitleLabelFirstBaselineLayoutConstraint; // @synthesize buttonTitleLabelFirstBaselineLayoutConstraint=_buttonTitleLabelFirstBaselineLayoutConstraint;
@property(readonly, nonatomic) double buttonTitleLabelFirstBaselineLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *buttonTitleLabelLastBaselineLayoutConstraint; // @synthesize buttonTitleLabelLastBaselineLayoutConstraint=_buttonTitleLabelLastBaselineLayoutConstraint;
@property(readonly, nonatomic) double buttonTitleLabelLastBaselineLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *buttonTrailingLayoutConstraint; // @synthesize buttonTrailingLayoutConstraint=_buttonTrailingLayoutConstraint;
@property(nonatomic, getter=isButtonHidden) _Bool buttonHidden;
- (void)loadConstraints;
- (void)loadView;
- (void)setButtonHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setButtonHidden:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (double)titleLabelFirstBaselineLayoutConstraintConstant;
- (double)titleLabelLastBaselineLayoutConstraintConstant;
- (void)updateConstraintsConstants;
- (void)updateFonts;

@end

