//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, TUCall;

@interface PHAudioDeviceController : NSObject
{
    NSDictionary *_pickedRoute;
}

+ (id)sharedAudioDeviceController;
- (void).cxx_destruct;
- (void)_audioRouteInformationChanged;
- (void)_pickRoute:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *_pickableRoutes;
- (id)_pickableRoutesForCategory:(id)arg1 mode:(id)arg2;
- (id)_pickedRoute;
- (_Bool)_routeIsAirTunes:(id)arg1;
- (_Bool)_routeIsDefault:(id)arg1;
- (_Bool)_routeIsHandset:(id)arg1;
- (_Bool)_routeIsReceiver:(id)arg1;
- (_Bool)_routeIsSpeaker:(id)arg1;
@property(readonly, nonatomic) TUCall *callForPickableRoutes;
- (void)clearCachedRoutes;
- (void)dealloc;
- (_Bool)handsetRouteAvailable;
- (id)init;
- (void)pickHandsetRoute;
- (void)pickRouteWithUID:(id)arg1;
- (void)pickSpeakerRoute;
@property(readonly, copy, nonatomic) NSDictionary *pickedRoute; // @synthesize pickedRoute=_pickedRoute;
- (_Bool)receiverRouteIsPicked;
- (void)restorePickedRoute;
@property(readonly, nonatomic) NSArray *routes;
- (_Bool)speakerRouteAvailable;
- (_Bool)speakerRouteIsPicked;

@end

