//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class PHRingHighlightView, UIColor, UIView, UIVisualEffectView;

@interface PHBottomBarButton : UIButton
{
    _Bool _usesSmallerFontSize;
    long long _orientation;
    UIColor *_originalBackgroundColor;
    UIVisualEffectView *_effectView;
    double _diameter;
    UIView *_overlayView;
    PHRingHighlightView *_ringView;
    struct CGSize _buttonSize;
}

+ (id)defaultFont;
- (void).cxx_destruct;
- (void)_performSetEnabled:(_Bool)arg1;
- (void)_performSetHighlighted:(_Bool)arg1;
- (void)_performSetSelected:(_Bool)arg1;
@property(nonatomic) struct CGSize buttonSize; // @synthesize buttonSize=_buttonSize;
@property(nonatomic) double diameter; // @synthesize diameter=_diameter;
@property(retain, nonatomic) UIVisualEffectView *effectView; // @synthesize effectView=_effectView;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (id)initWithConfiguration:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (id)newOverlayView;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) UIColor *originalBackgroundColor; // @synthesize originalBackgroundColor=_originalBackgroundColor;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
- (void)refreshForCallState:(long long)arg1;
@property(retain, nonatomic) PHRingHighlightView *ringView; // @synthesize ringView=_ringView;
- (void)setEnabled:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
@property(nonatomic) _Bool usesSmallerFontSize; // @synthesize usesSmallerFontSize=_usesSmallerFontSize;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;

@end

