//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHCarPlayGenericTableViewCell.h"

@class NSLayoutConstraint, UIDateLabel, UIImageView, UILabel, VMVoicemail;

@interface PHCarPlayVoicemailTableViewCell : PHCarPlayGenericTableViewCell
{
    VMVoicemail *_representedVoicemail;
    UILabel *_nameLabel;
    NSLayoutConstraint *_nameLabelBaselineConstraint;
    UILabel *_subtitleLabel;
    UIDateLabel *_dateLabel;
    UIImageView *_unreadIndicatorImageView;
}

- (void).cxx_destruct;
- (void)_voicemailFlagsDidChangeNotification:(id)arg1;
@property(retain) UIDateLabel *dateLabel; // @synthesize dateLabel=_dateLabel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain) NSLayoutConstraint *nameLabelBaselineConstraint; // @synthesize nameLabelBaselineConstraint=_nameLabelBaselineConstraint;
@property(retain, nonatomic) VMVoicemail *representedVoicemail; // @synthesize representedVoicemail=_representedVoicemail;
- (void)setPendingState:(_Bool)arg1;
@property(retain) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
- (void)setSubtitleString:(id)arg1;
@property(retain) UIImageView *unreadIndicatorImageView; // @synthesize unreadIndicatorImageView=_unreadIndicatorImageView;
- (void)updatePendingState;

@end

