//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface PHCarPlayGenericViewController : UIViewController
{
    _Bool _respondsToEventsWhileInCall;
}

- (void)hardwareControlEventNotification:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property _Bool respondsToEventsWhileInCall; // @synthesize respondsToEventsWhileInCall=_respondsToEventsWhileInCall;
- (_Bool)shouldRespondToHardwareControlEvent;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
@property(readonly) _Bool viewIsInAppearedState;

@end

