//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSLayoutConstraint, PHCarPlayInCallButtonRing, UIColor, UILabel;

@interface PHCarPlayInCallButton : UIButton
{
    _Bool _toggledOn;
    int _inCallButtonType;
    int _specialLayoutType;
    UILabel *_buttonLabel;
    NSLayoutConstraint *_horizontalPositioningConstraint;
    UIColor *_unhighlightedBackgroundColor;
    PHCarPlayInCallButtonRing *_ringView;
    long long _callState;
}

- (void).cxx_destruct;
@property(retain) UILabel *buttonLabel; // @synthesize buttonLabel=_buttonLabel;
@property(nonatomic) long long callState; // @synthesize callState=_callState;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
@property(retain) NSLayoutConstraint *horizontalPositioningConstraint; // @synthesize horizontalPositioningConstraint=_horizontalPositioningConstraint;
@property(readonly) int inCallButtonType; // @synthesize inCallButtonType=_inCallButtonType;
- (id)initForButtonType:(int)arg1 callState:(long long)arg2;
- (struct CGSize)intrinsicContentSize;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;
@property(retain) PHCarPlayInCallButtonRing *ringView; // @synthesize ringView=_ringView;
- (void)setEnabled:(_Bool)arg1;
- (void)setHasRingView:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
@property(nonatomic) int specialLayoutType; // @synthesize specialLayoutType=_specialLayoutType;
@property(nonatomic) _Bool toggledOn; // @synthesize toggledOn=_toggledOn;
@property(retain) UIColor *unhighlightedBackgroundColor; // @synthesize unhighlightedBackgroundColor=_unhighlightedBackgroundColor;
- (void)updateToProperIconColor;
- (id)viewForLastBaselineLayout;

@end

