//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PHCarPlayHardwareControlsBroadcaster : NSObject
{
    struct __IOHIDEventSystemClient *_hidEventSystemClientRef;
    NSString *_eventTypeToIgnore;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(retain) NSString *eventTypeToIgnore; // @synthesize eventTypeToIgnore=_eventTypeToIgnore;
- (id)init;
- (void)longPressTimerFired:(id)arg1;

@end

