//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHCarPlayGenericTableViewCell.h"

@class NSLayoutConstraint, UIDateLabel, UIImageView, UILabel;

@interface PHCarPlayRecentsTableViewCell : PHCarPlayGenericTableViewCell
{
    _Bool _showsOutgoingCallIcon;
    UIDateLabel *_dateLabel;
    UILabel *_nameLabel;
    NSLayoutConstraint *_nameLabelVerticalLayoutConstraint;
    UILabel *_phoneNumberTypeLabel;
    UIImageView *_outgoingCallIconImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIDateLabel *dateLabel; // @synthesize dateLabel=_dateLabel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) NSLayoutConstraint *nameLabelVerticalLayoutConstraint; // @synthesize nameLabelVerticalLayoutConstraint=_nameLabelVerticalLayoutConstraint;
@property(retain, nonatomic) UIImageView *outgoingCallIconImageView; // @synthesize outgoingCallIconImageView=_outgoingCallIconImageView;
@property(retain, nonatomic) UILabel *phoneNumberTypeLabel; // @synthesize phoneNumberTypeLabel=_phoneNumberTypeLabel;
@property(nonatomic) _Bool showsOutgoingCallIcon; // @synthesize showsOutgoingCallIcon=_showsOutgoingCallIcon;

@end

