//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHCarPlayGenericTableViewCell.h"

@class UIImageView, UILabel;

@interface PHCarPlayHardwareMenuTableViewCell : PHCarPlayGenericTableViewCell
{
    UILabel *_mainLabel;
    UIImageView *_iconImageView;
}

- (void).cxx_destruct;
@property(retain) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain) UILabel *mainLabel; // @synthesize mainLabel=_mainLabel;

@end

