//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHCarPlayGenericViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AVExternalDevice, NSString, PHCarPlayNoContentBannerView, UITableView, _UIFilteredDataSource;

@interface PHCarPlayGenericTableViewController : PHCarPlayGenericViewController <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _tableViewReloadIsRequiredOnViewWillAppear;
    UITableView *_mainTableView;
    _UIFilteredDataSource *_mainTableViewDataSource;
    PHCarPlayNoContentBannerView *_noContentBannerView;
    AVExternalDevice *_carPlayExternalDevice;
}

- (void).cxx_destruct;
- (_Bool)_viewControllerWasSelected;
- (void)applicationBadgeChangedNotification:(id)arg1;
@property(readonly) NSString *badgeString;
@property(retain) AVExternalDevice *carPlayExternalDevice; // @synthesize carPlayExternalDevice=_carPlayExternalDevice;
- (void)carPlayInCallViewControllerAppearedNotification:(id)arg1;
- (void)dealloc;
- (double)defaultRowHeight;
- (long long)filterType;
- (void)hardwareControlEventNotification:(id)arg1;
- (id)init;
- (void)limitedUIChanged:(id)arg1;
- (void)loadView;
@property(retain) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
@property(retain) _UIFilteredDataSource *mainTableViewDataSource; // @synthesize mainTableViewDataSource=_mainTableViewDataSource;
@property(retain) PHCarPlayNoContentBannerView *noContentBannerView; // @synthesize noContentBannerView=_noContentBannerView;
- (id)preferredFocusEnvironments;
- (void)programmaticallySelectRowAtIndexPath:(id)arg1;
- (void)setNoContentBannerShown:(_Bool)arg1;
@property _Bool tableViewReloadIsRequiredOnViewWillAppear; // @synthesize tableViewReloadIsRequiredOnViewWillAppear=_tableViewReloadIsRequiredOnViewWillAppear;
- (id)subtitleForNoContentBanner;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)titleForNoContentBanner;
- (void)updateBadgeString;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

