//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PHCarPlayHardwareControlsBroadcaster, PHCarPlayRootContainerViewController, UINavigationController, UIWindow;

@interface PHCarPlayManager : NSObject
{
    PHCarPlayRootContainerViewController *_containerViewController;
    UIWindow *_carPlayWindow;
    PHCarPlayHardwareControlsBroadcaster *_hardwareControlsBroadcaster;
    PHCarPlayRootContainerViewController *_rootContainerViewController;
}

+ (id)sharedCarPlayManager;
+ (_Bool)shouldLimitKeypadAccess;
- (void).cxx_destruct;
@property(readonly) _Bool activeInterfaceMechanismIsHardware;
- (void)attachCarPlayToScreen:(id)arg1;
@property(readonly) UINavigationController *carPlayNavigationController;
@property(retain) UIWindow *carPlayWindow; // @synthesize carPlayWindow=_carPlayWindow;
@property(retain) PHCarPlayRootContainerViewController *containerViewController; // @synthesize containerViewController=_containerViewController;
- (void)dealloc;
@property(retain) PHCarPlayHardwareControlsBroadcaster *hardwareControlsBroadcaster; // @synthesize hardwareControlsBroadcaster=_hardwareControlsBroadcaster;
- (id)init;
@property(retain) PHCarPlayRootContainerViewController *rootContainerViewController; // @synthesize rootContainerViewController=_rootContainerViewController;
- (void)screenDidConnectNotification:(id)arg1;
- (void)screenDidDisconnectNotification:(id)arg1;
- (void)screenshotCarPlayScreen;

@end

