//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray, NSMutableDictionary;

@interface PHCarPlayInCallButtonsView : UIView
{
    int _buttonsMode;
    float _buttonDistributionScalingFactor;
    id <PHCarPlayInCallButtonsViewDelegate> _delegate;
    long long _highlightedControlIndex;
    NSMutableDictionary *_buttonsDictionary;
    NSArray *_buttonsArray;
    NSMutableArray *_buttonDividerViews;
}

- (void).cxx_destruct;
- (void)applyHorizontalPositioningConstraintWithFraction:(float)arg1 forButton:(id)arg2;
- (void)applyHorizontalPositioningConstraintWithFraction:(float)arg1 forDividerView:(id)arg2;
@property float buttonDistributionScalingFactor; // @synthesize buttonDistributionScalingFactor=_buttonDistributionScalingFactor;
@property(retain) NSMutableArray *buttonDividerViews; // @synthesize buttonDividerViews=_buttonDividerViews;
- (id)buttonForButtonType:(int)arg1 createIfNecessary:(_Bool)arg2 createWithHorizontalPositionFraction:(float)arg3;
- (void)buttonWasTapped:(id)arg1;
@property(retain) NSArray *buttonsArray; // @synthesize buttonsArray=_buttonsArray;
@property(retain) NSMutableDictionary *buttonsDictionary; // @synthesize buttonsDictionary=_buttonsDictionary;
@property int buttonsMode; // @synthesize buttonsMode=_buttonsMode;
- (void)callModelChangedNotification:(id)arg1;
- (_Bool)canBecomeFirstResponder;
- (void)dealloc;
@property id <PHCarPlayInCallButtonsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (float)distributedFractionForUndistributedFraction:(float)arg1;
- (id)existingButtonsNotInArray:(id)arg1;
@property(nonatomic) long long highlightedControlIndex; // @synthesize highlightedControlIndex=_highlightedControlIndex;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)keyForButtonType:(int)arg1;
@property(readonly) long long numberOfControls;
- (void)phoneCallStatusChangedNotification:(id)arg1;
- (id)preferredFocusEnvironments;
- (void)removeButtons:(id)arg1;
- (void)setButtonsMode:(int)arg1 animated:(_Bool)arg2;
- (void)setMuted:(_Bool)arg1;
- (_Bool)shouldShowActionTypeSendToVoicemail;
- (void)updateButtonsForCallModelState;

@end

