//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHCarPlayGenericTableViewController.h"

@class MPRecentsController, NSMutableArray;

@interface PHCarPlayRecentsViewController : PHCarPlayGenericTableViewController
{
    MPRecentsController *_recentsController;
    NSMutableArray *_recentCalls;
    unsigned long long _unreadCallCount;
}

- (void).cxx_destruct;
- (void)applicationDidEnterBackgroundNotification:(id)arg1;
- (id)badgeString;
- (void)dealloc;
- (double)defaultRowHeight;
- (void)handleRecentsControllerRecentCallsDidChangeNotification:(id)arg1;
- (id)init;
- (void)programmaticallySelectRowAtIndexPath:(id)arg1;
- (id)recentCallAtIndex:(long long)arg1;
@property(retain, nonatomic) NSMutableArray *recentCalls; // @synthesize recentCalls=_recentCalls;
@property(retain, nonatomic) MPRecentsController *recentsController; // @synthesize recentsController=_recentsController;
@property(nonatomic) unsigned long long unreadCallCount; // @synthesize unreadCallCount=_unreadCallCount;
- (id)subtitleForNoContentBanner;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)titleForNoContentBanner;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

