//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHCarPlayGenericTableViewController.h"

@class NSMutableArray, NSMutableDictionary, TPFavoritesController, TUCallProviderManager;

@interface PHCarPlayFavoritesViewController : PHCarPlayGenericTableViewController
{
    TPFavoritesController *_favoritesController;
    NSMutableArray *_favoritesEntries;
    TUCallProviderManager *_callProviderManager;
    NSMutableDictionary *_transportNameCache;
}

- (void).cxx_destruct;
- (id)audioFavoritesEntryForFavoritesEntry:(id)arg1;
- (id)avatarViewContactForFavoritesEntry:(id)arg1;
@property(readonly, nonatomic) TUCallProviderManager *callProviderManager; // @synthesize callProviderManager=_callProviderManager;
- (void)dealloc;
- (double)defaultRowHeight;
@property(readonly, nonatomic) TPFavoritesController *favoritesController; // @synthesize favoritesController=_favoritesController;
@property(retain, nonatomic) NSMutableArray *favoritesEntries; // @synthesize favoritesEntries=_favoritesEntries;
- (id)favoritesEntryAtIndex:(long long)arg1;
- (void)handleTPFavoritesControllerFavoritesEntriesDidChangeNotification:(id)arg1;
- (id)init;
- (void)programmaticallySelectRowAtIndexPath:(id)arg1;
- (void)reloadDataForFavoritesEntries:(id)arg1;
- (void)setFavoritesEntries:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)subtitleForNoContentBanner;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)titleForNoContentBanner;
@property(readonly, copy, nonatomic) NSMutableDictionary *transportNameCache; // @synthesize transportNameCache=_transportNameCache;
- (id)transportNameForFavoritesEntry:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

