//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class VMVoicemailManager;

@interface PHCarPlayVoicemailManager : NSObject
{
    VMVoicemailManager *_voicemailManager;
}

+ (id)sharedVoicemailManager;
- (void).cxx_destruct;
- (void)_phoneApplicationAddressBookChangedNotification:(id)arg1;
- (id)badgeString;
- (void)dealloc;
- (id)init;
- (_Bool)isVisualVoicemailAvailable;
- (void)onlineStateChangedNotification:(id)arg1;
@property(retain, nonatomic) VMVoicemailManager *voicemailManager; // @synthesize voicemailManager=_voicemailManager;
- (void)subscribedStateChangedNotification:(id)arg1;
- (id)trashedVoicemails;
- (id)voicemailWithID:(unsigned long long)arg1;
- (id)voicemails;
- (void)voicemailsChangedNotification:(id)arg1;

@end

