//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSLayoutConstraint, UILabel;

@interface PHCarPlayPhoneCallViewCell : UIControl
{
    NSLayoutConstraint *_containerSpecificLeftConstraint;
    NSLayoutConstraint *_containerSpecificRightConstraint;
    UILabel *_mainLabel;
    UILabel *_subtitleLabel;
}

- (void).cxx_destruct;
- (_Bool)canBecomeFocused;
@property(retain) NSLayoutConstraint *containerSpecificLeftConstraint; // @synthesize containerSpecificLeftConstraint=_containerSpecificLeftConstraint;
@property(retain) NSLayoutConstraint *containerSpecificRightConstraint; // @synthesize containerSpecificRightConstraint=_containerSpecificRightConstraint;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain) UILabel *mainLabel; // @synthesize mainLabel=_mainLabel;
- (void)setDimmed:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setEnabled:(_Bool)arg1;
@property(retain) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
- (void)setTitle:(id)arg1 subtitle:(id)arg2 animated:(_Bool)arg3;

@end

