//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHCarPlayGenericDialerViewController.h"

@interface PHCarPlayDialerViewController : PHCarPlayGenericDialerViewController
{
}

- (void)_noOpGestureAction:(id)arg1;
- (_Bool)_viewControllerWasSelected;
- (void)callButtonPressed:(id)arg1;
- (void)dealloc;
- (void)deleteButtonHide:(id)arg1;
- (void)deleteButtonPressed:(id)arg1;
- (void)hardwareControlEventNotification:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)limitedUINotification:(id)arg1;
- (void)loadView;
- (void)postMessageOverlayIfNeeded;
- (id)preferredFocusEnvironments;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;
- (void)setLimitedSoftPhoneKeypad:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

