//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITabBarControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UIView;

@interface PHCarPlayMainMenuContainerViewController : UIViewController <UITabBarControllerDelegate, UITableViewDelegate, UITableViewDataSource>
{
    NSArray *_rootViewControllerDictionaries;
    UIView *_centralAreaContainerView;
    UIViewController *_selectedViewController;
}

- (void).cxx_destruct;
- (void)_initializeRootViewControllerDictionaries;
@property(retain) UIView *centralAreaContainerView; // @synthesize centralAreaContainerView=_centralAreaContainerView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (id)navigationItem;
- (id)preferredFocusEnvironments;
@property(retain) NSArray *rootViewControllerDictionaries; // @synthesize rootViewControllerDictionaries=_rootViewControllerDictionaries;
@property(retain) UIViewController *selectedViewController; // @synthesize selectedViewController=_selectedViewController;
- (_Bool)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

