//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHCarPlayGenericViewController.h"

@class PHCarPlayProgressView, UIButton, UILabel, VMVoicemail;

@interface PHCarPlayVoicemailPlayerViewController : PHCarPlayGenericViewController
{
    _Bool _firstAppearanceEvent;
    _Bool _isPlaying;
    VMVoicemail *_representedVoicemail;
    UILabel *_nameLabel;
    UILabel *_detailLabel;
    PHCarPlayProgressView *_progressView;
    UIButton *_callBackButton;
    UIButton *_rewindButton;
    UIButton *_playPauseButton;
}

+ (id)detailStringForVoicemail:(id)arg1;
- (void).cxx_destruct;
- (void)_handleApplicationDidEnterBackgroundNotification:(id)arg1;
- (void)_handleVoicemailPlayerDidPlayToEnd:(id)arg1;
- (void)_handleVoicemailPlayerDidStartPlaying:(id)arg1;
- (void)_handleVoicemailPlayerRateChanged:(id)arg1;
@property(retain) UIButton *callBackButton; // @synthesize callBackButton=_callBackButton;
- (void)callBackButtonTapped:(id)arg1;
- (void)dealloc;
@property(retain) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property _Bool firstAppearanceEvent; // @synthesize firstAppearanceEvent=_firstAppearanceEvent;
- (void)hardwareControlEventNotification:(id)arg1;
- (id)init;
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
- (void)loadView;
@property(retain) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain) UIButton *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
- (void)playPauseButtonTapped:(id)arg1;
@property(retain) PHCarPlayProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) VMVoicemail *representedVoicemail; // @synthesize representedVoicemail=_representedVoicemail;
@property(retain) UIButton *rewindButton; // @synthesize rewindButton=_rewindButton;
- (void)rewindButtonTapped:(id)arg1;
- (void)updatePlayPauseButton;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

