//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

@class NSString, _UIContentUnavailableView;

@interface PHCollectionViewController : UICollectionViewController
{
    _Bool _contentUnavailable;
    _UIContentUnavailableView *_contentUnavailableView;
    NSString *_contentUnavailableViewTitle;
    long long _whitePointAdaptivityStyle;
}

- (void).cxx_destruct;
- (void)addNotificationObservers;
- (void)commonInit;
@property(nonatomic) _Bool contentUnavailable; // @synthesize contentUnavailable=_contentUnavailable;
@property(retain, nonatomic) _UIContentUnavailableView *contentUnavailableView; // @synthesize contentUnavailableView=_contentUnavailableView;
@property(copy, nonatomic) NSString *contentUnavailableViewTitle; // @synthesize contentUnavailableViewTitle=_contentUnavailableViewTitle;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)handleApplicationDidBecomeActiveNotification:(id)arg1;
- (void)handleApplicationDidEnterBackgroundNotification:(id)arg1;
- (void)handleApplicationWillEnterForegroundNotification:(id)arg1;
- (void)handleContentSizeCategoryDidChangeNotification:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(readonly, nonatomic, getter=isForceTouchAvailable) _Bool forceTouchAvailable;
- (void)makeUIForDefaultPNG;
- (long long)preferredWhitePointAdaptivityStyle;
- (void)setContentUnavailable:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) long long whitePointAdaptivityStyle; // @synthesize whitePointAdaptivityStyle=_whitePointAdaptivityStyle;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

