//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CNContactStore;

@interface PHContactsClient : NSObject
{
    CNContactStore *_contactStore;
}

+ (id)contactsClient;
+ (id)contactsClientWithContactStore:(id)arg1;
+ (id)suggestedContactsClient;
- (void).cxx_destruct;
- (id)avatarContactFromContactIdentifier:(id)arg1;
- (id)contactForCall:(id)arg1;
@property(retain) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
- (id)init;
- (id)initWithContactStore:(id)arg1;

@end

