//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RadiosPreferencesDelegate.h"

@class NSObject<OS_dispatch_queue>, RadiosPreferences, UIImage;

@interface PHDevice : NSObject <RadiosPreferencesDelegate>
{
    _Bool _cellularRadioEnabled;
    _Bool _ringerSwitchEnabled;
    _Bool _proximitySensorState;
    int _ringerStateNotifyToken;
    unsigned long long _ttyTransportMethod;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    RadiosPreferences *_radiosPreferences;
}

+ (id)currentDevice;
- (void).cxx_destruct;
- (void)airplaneModeChanged;
@property(readonly, nonatomic) UIImage *audioRouteGlyphImage;
- (void)dealloc;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (_Bool)fetchCellularRadioEnabled;
- (unsigned long long)fetchCurrentTTYTransportMethod;
- (_Bool)fetchRingerSwitchEnabled;
- (void)handleTTYTransportMethodChangedNotification:(id)arg1;
- (id)init;
@property(nonatomic, getter=isCellularRadioEnabled) _Bool cellularRadioEnabled; // @synthesize cellularRadioEnabled=_cellularRadioEnabled;
@property(nonatomic, getter=isRingerSwitchEnabled) _Bool ringerSwitchEnabled; // @synthesize ringerSwitchEnabled=_ringerSwitchEnabled;
@property(readonly, nonatomic) _Bool isTTYAvailable;
- (void)loadPropertiesOnConcurrentQueue;
@property(nonatomic) _Bool proximitySensorState; // @synthesize proximitySensorState=_proximitySensorState;
@property(retain, nonatomic) RadiosPreferences *radiosPreferences; // @synthesize radiosPreferences=_radiosPreferences;
- (void)registerForRingerStateNotifications;
- (void)registerForTTYTransportMethodNotifications;
@property(nonatomic) int ringerStateNotifyToken; // @synthesize ringerStateNotifyToken=_ringerStateNotifyToken;
@property(nonatomic) unsigned long long ttyTransportMethod; // @synthesize ttyTransportMethod=_ttyTransportMethod;
- (unsigned long long)stateForNotifyToken:(int)arg1;
- (void)unregisterForRingerStateNotifications;

@end

