//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHTableViewCell.h"

@interface PHDoubleLineTableViewCell : PHTableViewCell
{
}

- (void)loadConstraints;
- (void)loadContentView;
@property(readonly, nonatomic) double subtitleLabelFirstBaselineLayoutConstraintConstant;
@property(readonly, nonatomic) double subtitleLabelLastBaselineLayoutConstraintConstant;
@property(readonly, nonatomic) double titleLabelFirstBaselineLayoutConstraintConstant;
- (void)updateConstraintsConstants;

@end

