//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "DialerLCDFieldProtocol.h"
#import "PHLCDViewTextFieldDelegate.h"
#import "UITextFieldDelegate.h"

@class NSArray, NSString, PHLCDViewTextField, UIButton, UILabel;

@interface PHHandsetDialerLCDView : UIView <PHLCDViewTextFieldDelegate, UITextFieldDelegate, DialerLCDFieldProtocol>
{
    _Bool _addContactButtonVisible;
    _Bool _deleteButtonVisible;
    _Bool _highlighted;
    _Bool _inCallMode;
    int _dialerType;
    UIButton *_addContactButton;
    UILabel *_contactLabel;
    id <DialerLCDFieldDelegate> _delegate;
    PHLCDViewTextField *_numberTextField;
    NSArray *_numberLabelHorizontalConstraints;
}

- (void).cxx_destruct;
- (void)_makeCalloutVisible:(_Bool)arg1;
- (void)_menuDidHide:(id)arg1;
- (void)_requestMakeCutCopyPasteCalloutVisible:(_Bool)arg1;
@property(retain) UIButton *addContactButton; // @synthesize addContactButton=_addContactButton;
- (void)addContactPressed:(id)arg1;
- (float)addNumberFontSize;
- (void)applyLayoutConstraints;
- (id)attributedStringForName:(id)arg1 label:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
@property(retain) UILabel *contactLabel; // @synthesize contactLabel=_contactLabel;
- (void)copy:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <DialerLCDFieldDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteCharacter;
@property(nonatomic) int dialerType; // @synthesize dialerType=_dialerType;
- (void)endEditing;
- (id)generateNumberLabelHorizontalConstraints;
- (void)handleTapGesture:(id)arg1;
@property(nonatomic) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) _Bool inCallMode; // @synthesize inCallMode=_inCallMode;
- (id)initWithFrame:(struct CGRect)arg1 forDialerType:(int)arg2;
- (void)insertStringAtCurrentPosition:(id)arg1;
- (void)insertStringAtCurrentPosition:(id)arg1 deletingPreviousCharacter:(_Bool)arg2;
- (struct CGSize)intrinsicContentSize;
@property(readonly, nonatomic, getter=isMenuVisible) _Bool menuVisible;
- (id)lcdColor;
- (double)nameAndLabelFontSize;
- (id)newAddContactButton;
- (id)numberLabelFont;
@property(retain) NSArray *numberLabelHorizontalConstraints; // @synthesize numberLabelHorizontalConstraints=_numberLabelHorizontalConstraints;
- (double)numberLabelMaximumFontSize;
- (float)numberLabelMinimumFontSize;
@property(retain, nonatomic) PHLCDViewTextField *numberTextField; // @synthesize numberTextField=_numberTextField;
- (void)paste:(id)arg1;
- (_Bool)resignFirstResponder;
- (void)setName:(id)arg1 numberLabel:(id)arg2;
- (void)setName:(id)arg1 numberLabel:(id)arg2 suggestion:(_Bool)arg3;
- (void)setText:(id)arg1 needsFormat:(_Bool)arg2;
- (void)setText:(id)arg1 needsFormat:(_Bool)arg2 name:(id)arg3 label:(id)arg4;
- (_Bool)shouldInsertStringAtCurrentPosition:(id)arg1 deletingPreviousCharacter:(_Bool)arg2;
- (float)spacingBetweenNumberBaselineAndNameBaseline;
- (id)text;
- (void)textField:(id)arg1 didPasteString:(id)arg2;
- (void)textField:(id)arg1 didUpdateString:(id)arg2;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)updateAddAndDeleteButtonForText:(id)arg1 name:(id)arg2 animated:(_Bool)arg3;
- (void)updateAddAndDeleteButtonForText:(id)arg1 name:(id)arg2 label:(id)arg3 suggestion:(_Bool)arg4 animated:(_Bool)arg5;
- (void)updateNumberLabelHorizontalConstraints;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

