//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface PHHIDEventMonitor : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    struct __IOHIDEventSystemClient *_HIDEventSystemClient;
}

+ (id)HIDEventMonitor;
- (void).cxx_destruct;
@property(nonatomic) struct __IOHIDEventSystemClient *HIDEventSystemClient; // @synthesize HIDEventSystemClient=_HIDEventSystemClient;
- (void)dealloc;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void)handleKeyboardEvent:(struct __IOHIDEvent *)arg1;
- (id)init;
- (void)start;
- (void)stop;
- (id)stringFromIOHIDUsage:(long long)arg1;
- (id)stringFromIOHIDUsagePage:(long long)arg1;

@end

