//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "FBSDisplayLayoutObserver.h"

@class FBSDisplayLayoutMonitor, NSString, PHLocalVideoDisabledOverlayView, UIControl, UIView;

@interface PHLocalVideoViewController : UIViewController <FBSDisplayLayoutObserver>
{
    _Bool _localVideoAlwaysMatchesScreen;
    _Bool _supportsAutoRotation;
    _Bool _showsLocalPreviewStatusBarGradient;
    _Bool _waitingForLocalVideoFirstFrame;
    UIControl *_videoGroupView;
    UIView *_localVideoView;
    UIView *_localVideoStatusBarGradientView;
    PHLocalVideoDisabledOverlayView *_disabledOverlayView;
    long long _lastKnownOrientation;
    FBSDisplayLayoutMonitor *_displayLayoutMonitor;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
- (void).cxx_destruct;
- (void)_adjustForOrientationAnimated:(_Bool)arg1;
- (void)_applicationDidBecomeActive:(id)arg1;
- (void)_applicationWillResignActive:(id)arg1;
- (void)_applyAutoRotationCorrectionForOrientation:(long long)arg1 withTransitionCoordinator:(id)arg2;
- (void)_autoFadeInLocalVideo;
- (void)_avFirstPreviewFrameArrived:(id)arg1;
- (void)_dissociateVideoLayers;
- (void)_ensureLocalVideoWillBecomeVisible;
- (void)_ensureVideoLayersExist;
- (void)_fadeInLocalVideo;
- (void)_handleLocalCameraAvailableNotification:(id)arg1;
- (void)_handleLocalCameraErrorNotification:(id)arg1;
- (void)_handleOrientationDidChangeNotification:(id)arg1;
- (void)_handleVideoPreviewDidStartNotification:(id)arg1;
- (_Bool)_isInCallServiceShowingInDisplayLayout:(id)arg1;
- (_Bool)_isValidFaceTimeOrientation:(long long)arg1;
- (void)_setupVideoLayers;
- (int)_tuVideoDeviceOrientationForDeviceOrientation:(long long)arg1;
- (void)_updateLocalPreviewStatusBarGradient;
- (void)_updateLocalVideoOrientationAnimated:(_Bool)arg1;
- (void)associateLocalVideoLayers;
- (void)dealloc;
@property(retain, nonatomic) PHLocalVideoDisabledOverlayView *disabledOverlayView; // @synthesize disabledOverlayView=_disabledOverlayView;
@property(retain, nonatomic) FBSDisplayLayoutMonitor *displayLayoutMonitor; // @synthesize displayLayoutMonitor=_displayLayoutMonitor;
- (void)fadeInAnimated:(_Bool)arg1;
- (void)fadeOutAnimated:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) long long lastKnownOrientation; // @synthesize lastKnownOrientation=_lastKnownOrientation;
- (void)layoutMonitor:(id)arg1 didUpdateDisplayLayout:(id)arg2 withContext:(id)arg3;
- (void)loadView;
@property(nonatomic) _Bool localVideoAlwaysMatchesScreen; // @synthesize localVideoAlwaysMatchesScreen=_localVideoAlwaysMatchesScreen;
@property(retain, nonatomic) UIView *localVideoStatusBarGradientView; // @synthesize localVideoStatusBarGradientView=_localVideoStatusBarGradientView;
@property(retain, nonatomic) UIView *localVideoView; // @synthesize localVideoView=_localVideoView;
- (long long)preferredWhitePointAdaptivityStyle;
@property(nonatomic) _Bool showsLocalPreviewStatusBarGradient; // @synthesize showsLocalPreviewStatusBarGradient=_showsLocalPreviewStatusBarGradient;
@property(nonatomic) _Bool supportsAutoRotation; // @synthesize supportsAutoRotation=_supportsAutoRotation;
@property(retain, nonatomic) UIControl *videoGroupView; // @synthesize videoGroupView=_videoGroupView;
@property(nonatomic) _Bool waitingForLocalVideoFirstFrame; // @synthesize waitingForLocalVideoFirstFrame=_waitingForLocalVideoFirstFrame;
- (_Bool)shouldDisableEdgeClip;
- (void)startPreview;
- (void)stopPreview;
- (unsigned long long)supportedInterfaceOrientations;
- (void)updateLocalVideoToMatchScreen;
- (void)updateViewControllerForOrientation:(long long)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

