//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "PhoneTabViewController.h"

@class NSString, UIViewController<PhoneTabViewController>;

@interface PhoneNavigationController : UINavigationController <PhoneTabViewController>
{
    UIViewController<PhoneTabViewController> *_rootController;
}

+ (CDStruct_5ec447a9)badge;
+ (id)defaultPNGName;
+ (id)tabBarIconImage;
+ (id)tabBarIconName;
+ (int)tabViewType;
- (void).cxx_destruct;
- (void)_updateRootViewController;
- (void)dealloc;
- (void)handleURL:(id)arg1;
- (id)initWithRootViewController:(id)arg1;
- (void)prepareForSnapshot;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (id)rootViewController;
- (void)setViewControllers:(id)arg1;
- (_Bool)shouldSnapshot;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

