//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

#import "PhoneBaseViewController.h"
#import "UITabBarControllerDelegate.h"

@class MPFavoritesTableViewController, MPKeypadViewController, MPRecentsTableViewController, NSString, PHContactsViewController, PHVoicemailNavigationController, PhoneNavigationController, UINavigationController, UIToolbar;

@interface PhoneTabBarController : UITabBarController <UITabBarControllerDelegate, PhoneBaseViewController>
{
    PhoneNavigationController *_favoritesNavigationController;
    PhoneNavigationController *_recentsNavigationController;
    MPRecentsTableViewController *_recentsViewController;
    PHContactsViewController *_contactsViewController;
    PHVoicemailNavigationController *_voicemailViewController;
    _Bool _shouldSwitchToMostRecentViewType;
    MPFavoritesTableViewController *_favoritesViewController;
    MPKeypadViewController *_keypadViewController;
    UIToolbar *_toolbar;
}

+ (id)defaultPNGName;
+ (long long)statusBarStyle;
- (void).cxx_destruct;
- (void)_badgeChanged:(id)arg1;
- (void)_startListeningForBadgeChangedNotifications:(id)arg1;
- (void)_stopListeningForBadgeChangedNotifications:(id)arg1;
- (void)_updateAllBadges:(_Bool)arg1;
- (void)_updateBottomTabs;
- (void)_willAppearInRemoteViewController;
- (void)applicationDidResume;
- (void)applicationWillSuspend;
@property(retain, nonatomic) PHContactsViewController *contactsViewController; // @synthesize contactsViewController=_contactsViewController;
- (int)currentTabViewType;
- (void)dealloc;
- (int)defaultTabViewType;
@property(retain, nonatomic) UINavigationController *favoritesNavigationController; // @synthesize favoritesNavigationController=_favoritesNavigationController;
@property(retain, nonatomic) MPFavoritesTableViewController *favoritesViewController; // @synthesize favoritesViewController=_favoritesViewController;
- (void)handleURL:(id)arg1;
- (_Bool)handleUserActivityContinuation:(id)arg1;
- (id)init;
@property(retain, nonatomic) MPKeypadViewController *keypadViewController; // @synthesize keypadViewController=_keypadViewController;
- (void)popCurrentNavigationControllerToRootViewControllerIfAppropriate;
- (void)prepareForSnapshot;
@property(retain, nonatomic) UINavigationController *recentsNavigationController; // @synthesize recentsNavigationController=_recentsNavigationController;
@property(retain, nonatomic) MPRecentsTableViewController *recentsViewController; // @synthesize recentsViewController=_recentsViewController;
- (void)registerForBadgeUpdateNotification;
- (void)resetViewController;
- (void)setSelectedViewController:(id)arg1;
@property _Bool shouldSwitchToMostRecentViewType; // @synthesize shouldSwitchToMostRecentViewType=_shouldSwitchToMostRecentViewType;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) PHVoicemailNavigationController *voicemailViewController; // @synthesize voicemailViewController=_voicemailViewController;
- (_Bool)shouldDisableEdgeClip;
- (_Bool)shouldSnapshot;
- (void)showFavoritesTab:(_Bool)arg1 recentsTab:(_Bool)arg2 contactsTab:(_Bool)arg3 keypadTab:(_Bool)arg4 voicemailTab:(_Bool)arg5;
- (void)switchToMostRecentlyUsedTabType;
- (void)switchToTab:(int)arg1;
- (_Bool)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (int)tabTypeForViewController:(id)arg1;
- (void)transitionCompleted;
- (void)updateUserActivityState:(id)arg1;
- (id)viewControllerForTabViewType:(int)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

