//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PhoneTabViewController.h"

@class NSString;

@interface PhoneViewController : UIViewController <PhoneTabViewController>
{
    double _cachedCellHeight;
    Class _cellClassForCachedCellHeight;
}

+ (CDStruct_5ec447a9)badge;
+ (void)cacheFinishedTabBarIconImage:(id)arg1 withTabBarItemName:(id)arg2;
+ (id)defaultPNGName;
+ (void)initializeIconAndTitle:(id)arg1;
+ (_Bool)tabBarIconImageFinished:(id *)arg1 forTabBarItemName:(id)arg2;
+ (id)tabBarIconName;
+ (int)tabViewType;
- (void).cxx_destruct;
- (void)_loadOffsetDefaultForKey:(id)arg1 withScrollView:(id)arg2;
- (void)_prepareForLoadView;
- (void)_saveOffsetDefaultForKey:(id)arg1 withScrollView:(id)arg2;
- (void)_updateCachedCellHeight;
@property double cachedCellHeight; // @synthesize cachedCellHeight=_cachedCellHeight;
@property(retain, nonatomic) Class cellClassForCachedCellHeight; // @synthesize cellClassForCachedCellHeight=_cellClassForCachedCellHeight;
- (void)contentSizeCategoryDidChange;
- (id)init;
- (void)prepareForSnapshot;
- (void)savePreferences;
- (_Bool)shouldSnapshot;
- (unsigned long long)supportedInterfaceOrientations;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

