//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

#import "UIApplicationDelegate.h"

@class NSArray, NSString, PhoneRootViewController, TUMetadataCache, UIColor, UIWindow;

@interface PhoneApplication : UIApplication <UIApplicationDelegate>
{
    PhoneRootViewController *_rootController;
    UIWindow *_window;
    double _launchTime;
    NSString *_cachedApplicationBadgeString;
    TUMetadataCache *_metadataCache;
    _Bool _headerViewShowsAllRecentCalls;
    _Bool _audioButtonAllowsPhoneCallsAndFaceTimeAudio;
    _Bool _suspendingApplication;
    _Bool _resumingApplication;
    long long _headerViewNumberOfCallsToShow;
    unsigned long long _unreadCallCount;
    NSArray *_recentCalls;
}

+ (_Bool)authorizedToUseContactStore;
+ (id)contactStore;
+ (void)contactStoreDidChange:(id)arg1;
+ (void)initialize;
+ (unsigned long long)optionsForContactStore;
+ (void)preloadContactStoreIfNecessary;
+ (id)sharedNumberFormatter;
- (void).cxx_destruct;
- (void)TestAddUnknownFavorite;
- (_Bool)_activeFaceTimeCallExists;
- (id)_createRecentCallWithCallerId:(id)arg1;
- (_Bool)_faceTimeInvitationExists;
- (void)_forceWindowFront;
- (void)_initializeUI;
- (void)_localeChangedNotification:(id)arg1;
- (void)_releaseAddressBook;
- (void)_resetCurrentViewController;
- (void)_revertAddressBook;
- (void)_scroll;
- (id)_tableFromViewController:(id)arg1;
- (void)accessibilitySettingsChangedNotification:(id)arg1;
- (_Bool)activeFaceTimeCallExists;
- (void *)addressBook;
@property(readonly, nonatomic) _Bool alwaysShowLocalVideo;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationDidResume;
- (void)applicationDidResumeForEventsOnly;
- (void)applicationOpenURL:(id)arg1;
- (_Bool)applicationSuspendWithSettings:(id)arg1;
@property(readonly) UIColor *applicationTintColor;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillSuspendForEventsOnly;
@property(readonly, nonatomic) _Bool audioButtonAllowsPhoneCallsAndFaceTimeAudio; // @synthesize audioButtonAllowsPhoneCallsAndFaceTimeAudio=_audioButtonAllowsPhoneCallsAndFaceTimeAudio;
- (_Bool)authorizedToUseAddressBook;
- (_Bool)authorizedToUseContactStore;
@property(readonly, nonatomic) long long backdropStyle;
@property(readonly, nonatomic) _Bool badgesMissedFaceTimeAudio;
@property(readonly, nonatomic) _Bool badgesMissedFaceTimeVideo;
@property(readonly, nonatomic) _Bool badgesMissedTelephonyCalls;
- (id)callHistoryController;
- (unsigned long long)callHistoryControllerOptions;
- (id)callHistoryControllerWithCoalescingStrategy:(unsigned long long)arg1;
- (void)callHistoryUnreadCallCountDidChange:(id)arg1;
- (id)contactStore;
@property(readonly, nonatomic) _Bool contentViewAnimationsFadeInsteadOfMove;
@property(readonly, nonatomic) _Bool contentViewCanRotate;
@property(readonly, nonatomic) unsigned int contentViewOffscreenEdge;
- (void)dealloc;
@property(readonly, nonatomic) int defaultAction;
@property(readonly, nonatomic) _Bool defaultActionIsFaceTimeAudio;
@property(readonly, nonatomic) _Bool defaultActionIsFaceTimeVideo;
@property(readonly, nonatomic) _Bool defaultActionIsTelephonyCall;
- (_Bool)dialVoicemail;
- (void)didReceiveMemoryWarning;
- (void *)existingAddressBook;
- (_Bool)faceTimeAudioIsAvailable;
- (_Bool)faceTimeInvitationExists;
- (_Bool)faceTimeVideoIsAvailable;
- (void)failTestOnMainThread:(id)arg1 reason:(id)arg2;
- (void)finishTestOnMainThread:(id)arg1;
- (void)handleApplicationFinishedSnapshottingNotification:(id)arg1;
- (void)handleIDSServiceAvailabilityDidChangeNotification:(id)arg1;
@property(readonly, nonatomic) _Bool hasEnhancedVoicemail;
@property(readonly, nonatomic) long long headerViewNumberOfCallsToShow; // @synthesize headerViewNumberOfCallsToShow=_headerViewNumberOfCallsToShow;
@property(readonly, nonatomic) _Bool headerViewShowsAllRecentCalls; // @synthesize headerViewShowsAllRecentCalls=_headerViewShowsAllRecentCalls;
- (_Bool)inCall;
- (_Bool)inFaceTime;
- (_Bool)isDeviceCapableOfFaceTimeAudio;
- (_Bool)isDeviceCapableOfFaceTimeVideo;
- (_Bool)isDeviceCapableOfTelephonyCalls;
- (_Bool)isLowGraphicsPerformanceDevice;
- (double)launchTime;
- (id)nameOfDefaultImageToUpdateAtSuspension;
- (_Bool)openURL:(id)arg1;
- (void)openURL:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (struct CGRect)phoneViewTabBarContentFrame;
- (void)prepareForDefaultImageSnapshotForScreen:(id)arg1;
@property(copy, nonatomic) NSArray *recentCalls; // @synthesize recentCalls=_recentCalls;
- (void)requestSuspendAfterLastCall;
- (void)requestSuspendWithTransparencyAfterLastCall;
@property(readonly, nonatomic) _Bool resumingApplication; // @synthesize resumingApplication=_resumingApplication;
- (id)rootViewController;
- (void)runSwitchTabTest:(id)arg1 fromTab:(int)arg2 switchTo:(int)arg3 numberOfIterations:(int)arg4;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
- (void)setIgnoresInteractionEvents:(_Bool)arg1;
@property(nonatomic) unsigned long long unreadCallCount; // @synthesize unreadCallCount=_unreadCallCount;
@property(readonly, nonatomic) _Bool shouldHideVoicemailUI;
- (_Bool)shouldSnapshot;
- (void)showInitialView;
@property(readonly, nonatomic) _Bool showSplashScreenOnSignin;
- (_Bool)showsCallsFromService:(int)arg1;
@property(readonly, nonatomic) _Bool showsFaceTimeAudio;
@property(readonly, nonatomic) _Bool showsFaceTimeAudioFavorites;
@property(readonly, nonatomic) _Bool showsFaceTimeAudioRecents;
@property(readonly, nonatomic) _Bool showsFaceTimeVideo;
@property(readonly, nonatomic) _Bool showsFaceTimeVideoFavorites;
@property(readonly, nonatomic) _Bool showsFaceTimeVideoRecents;
@property(readonly, nonatomic) _Bool showsPhoneDialer;
@property(readonly, nonatomic) _Bool showsPhoneVoicemail;
@property(readonly, nonatomic) _Bool showsTelephonyCalls;
@property(readonly, nonatomic) _Bool showsTelephonyFavorites;
@property(readonly, nonatomic) _Bool showsTelephonyRecents;
@property(readonly, nonatomic) _Bool showsThirdPartyRecents;
- (void)startScrollTest;
- (void)startSwitchTest:(int)arg1;
- (void)startTestOnMainThread:(id)arg1;
@property(readonly, nonatomic) _Bool suspendingApplication; // @synthesize suspendingApplication=_suspendingApplication;
@property(readonly, nonatomic) _Bool tabBarCanSlide;
@property(readonly, nonatomic) _Bool tabBarFillsScreen;
- (_Bool)telephonyCallingIsAvailable;
- (void)userDefaultsDidChange:(id)arg1;
- (int)userInterfaceScreenType;
@property(readonly, nonatomic) unsigned int userInterfaceStyle;
@property(readonly, nonatomic) _Bool usesBlendModes;
@property(readonly, nonatomic) _Bool usesUnifiedInterface;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

