//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, NSUserActivity;

@protocol PhoneBaseViewController <NSObject>
+ (NSString *)defaultPNGName;
+ (long long)statusBarStyle;
- (_Bool)handleUserActivityContinuation:(NSUserActivity *)arg1;
- (void)prepareForSnapshot;
- (void)resetViewController;
- (_Bool)shouldDisableEdgeClip;
- (_Bool)shouldSnapshot;

@optional
- (void)handleURL:(NSURL *)arg1;
- (void)prepareToHandleURL:(NSURL *)arg1;
- (void)updateViewControllerForOrientation:(long long)arg1;
@end

