//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class PHFrecentViewController, PHLocalVideoViewController, PHRegistrationViewController, PhoneContentView, UIViewController<PhoneBaseViewController>, _UIBackdropView;

@interface PhoneRootViewController : UIViewController
{
    PhoneContentView *_contentView;
    PHRegistrationViewController *_registrationController;
    PHLocalVideoViewController *_localVideoViewController;
    PHFrecentViewController *_faceTimeRecentViewController;
    _Bool _faceTimeRegistrationViewIsShowing;
    UIViewController<PhoneBaseViewController> *_baseViewController;
    _UIBackdropView *_backdropView;
    UIViewController *_detailsViewController;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
- (void).cxx_destruct;
- (id)_childViewControllerForWhitePointAdaptivityStyle;
- (void)_constrainRegistrationView;
- (double)_contentViewWidthForApplicationBoundsSize:(struct CGSize)arg1;
- (void)_ensureProperPositionForContentView;
- (void)_getRotationContentSettings:(CDStruct_e950349b *)arg1;
- (void)_stausBarDidChangeFrame:(id)arg1;
- (void)animateInUI;
@property(readonly, nonatomic) CDStruct_5ec447a9 applicationBadge;
@property(readonly, retain, nonatomic) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
@property(readonly, retain, nonatomic) UIViewController<PhoneBaseViewController> *baseViewController; // @synthesize baseViewController=_baseViewController;
@property(readonly, retain, nonatomic) PhoneContentView *contentView;
- (void)createFaceTimeFirstRunViewIfNeeded;
- (void)destroyFirstRunController;
@property(retain) UIViewController *detailsViewController; // @synthesize detailsViewController=_detailsViewController;
- (void)ensureBaseViewControllerIsShowing;
@property(readonly, retain, nonatomic) PHFrecentViewController *faceTimeRecentViewController; // @synthesize faceTimeRecentViewController=_faceTimeRecentViewController;
- (void)handleApplicationWillEnterForegroundNotification:(id)arg1;
- (void)hideContentViewAnimated:(_Bool)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)hideDetailsViewController;
- (void)hideVideoConferenceBackgroundViewAnimated:(_Bool)arg1;
- (_Bool)isContentViewLoaded;
- (void)loadView;
@property(readonly, retain, nonatomic) PHLocalVideoViewController *localVideoViewController;
- (void)setContentViewHiddenPosition;
- (void)setContentViewNormalPosition;
- (void)setupContentViewFullSize;
- (void)setupContentViewSidebar;
- (_Bool)shouldAutorotate;
- (void)showContentViewAnimated:(_Bool)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)showDetailsViewController;
- (void)showFaceTimeFirstRunViewIfNeeded;
- (void)showVideoConferenceBackgroundViewAnimated:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

