//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PHUIConfiguration : NSObject
{
}

+ (double)bottomOffsetForFaceTimeUIInLandscapeMode;
+ (_Bool)canAutoRotateInCallUIForFaceTime;
+ (_Bool)canAutoRotateInCallUIForFaceTimeAudio;
+ (_Bool)canRotateInCallUIOverlayForFaceTime;
+ (unsigned long long)contentViewSizeForFaceTime;
+ (id)dialerColor;
+ (double)dialerLCDFontSize;
+ (double)dialerLCDFontSizeInCall;
+ (double)dialerLCDLabelFontSize;
+ (double)dialerLCDLabelFontSizeInCall;
+ (unsigned long long)handsetDialerSize;
+ (unsigned long long)handsetDialerSpacing;
+ (unsigned long long)inCallBottomBarLowerOffset;
+ (unsigned long long)inCallBottomBarMaxTitleSize;
+ (unsigned long long)inCallBottomBarSpacing;
+ (unsigned long long)inCallControlAlignment;
+ (unsigned long long)inCallControlSize;
+ (unsigned long long)inCallControlSpacing;
+ (unsigned long long)inCallFaceTimeOverlayUISize;
+ (double)pipPartialHomeOffset;
+ (double)pipRadius;
+ (unsigned long long)pipStatusBarPadding;
+ (double)pipWallInset;
+ (double)pipWidth;
+ (_Bool)preferShorterStrings;
+ (unsigned long long)screenSize;
+ (_Bool)shouldUseFullScreenPeoplePicker;
+ (unsigned long long)tableViewCellVerticalSpacing;
+ (double)topOffsetForFaceTimeUIInLandscapeMode;
+ (unsigned long long)voicemailLayoutSpacing;
+ (double)yOffsetForDialerLCDView;
+ (double)yOffsetForParticipantsView;
+ (double)yParticipantsViewAdjustmentForKeypad;

@end

