//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "PHVoicemailGreetingModelDelegate.h"
#import "PHVoicemailGreetingPlaybackCellDelegate.h"

@class NSString, PHVoicemailGreetingModel, UIBarButtonItem;

@interface PHVoicemailGreetingViewController : UITableViewController <PHVoicemailGreetingPlaybackCellDelegate, PHVoicemailGreetingModelDelegate>
{
    _Bool _presentedFromSetup;
    _Bool _hasRecordedNewGreeting;
    id <PHVoicemailGreetingViewControllerDelegate> _greetingDelegate;
    PHVoicemailGreetingModel *_greetingModel;
    unsigned long long _selectedGreetingType;
    UIBarButtonItem *_saveItem;
    UIBarButtonItem *_progressItem;
}

- (void).cxx_destruct;
- (void)_cancelButtonTapped;
- (void)_handleDeactivation:(id)arg1;
- (void)_saveButtonTapped;
- (void)_selectCell:(id)arg1;
- (id)_selectedCellIndexPath;
- (id)_titleForCellAtIndexPath:(id)arg1;
- (void)dealloc;
@property id <PHVoicemailGreetingViewControllerDelegate> greetingDelegate; // @synthesize greetingDelegate=_greetingDelegate;
@property(retain, nonatomic) PHVoicemailGreetingModel *greetingModel; // @synthesize greetingModel=_greetingModel;
@property(nonatomic) _Bool hasRecordedNewGreeting; // @synthesize hasRecordedNewGreeting=_hasRecordedNewGreeting;
- (id)init;
@property(getter=isPresentedFromSetup) _Bool presentedFromSetup; // @synthesize presentedFromSetup=_presentedFromSetup;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)playStopButtonTapped;
- (id)playbackControlsCell;
@property(retain, nonatomic) UIBarButtonItem *progressItem; // @synthesize progressItem=_progressItem;
- (void)recordStopButtonTapped;
@property(retain, nonatomic) UIBarButtonItem *saveItem; // @synthesize saveItem=_saveItem;
@property(nonatomic) unsigned long long selectedGreetingType; // @synthesize selectedGreetingType=_selectedGreetingType;
- (id)sliderCell;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)voicemailGreetingAudioControllerDidChangeState:(long long)arg1;
- (void)voicemailGreetingDidFinishRecording;
- (void)voicemailGreetingDidSave;
- (void)voicemailGreetingDurationChanged:(double)arg1;
- (void)voicemailGreetingFailedWithError:(id)arg1;
- (void)voicemailGreetingPlayingProgressChanged:(double)arg1;
- (void)voicemailGreetingRecordingProgressChanged:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

