//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSIndexPath, NSString;

@protocol PHVoicemailListProtocol
+ (_Bool (^)(VMVoicemail *))voicemailPredicate;
@property(readonly, copy, nonatomic) NSString *folderName;
@property(readonly, nonatomic) _Bool hasContentToDisplay;
- (void)performTableViewDestructiveActionAtIndexPath:(NSIndexPath *)arg1;

@optional
@property(readonly, copy, nonatomic) NSString *messageCountText;
- (void)performTableViewRestoreActionAtIndexPath:(NSIndexPath *)arg1;
- (void)willShowVoicemails:(NSArray *)arg1;
@end

