//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPVoicemailTableViewController.h"

#import "PHVoicemailListProtocol.h"

@class NSString;

@interface PHVoicemailTrashListViewController : MPVoicemailTableViewController <PHVoicemailListProtocol>
{
}

+ (CDUnknownBlockType)voicemailPredicate;
- (id)cellDetailDestructiveActionText;
- (void)clearAllTapped;
@property(readonly, copy, nonatomic) NSString *folderName;
@property(readonly, nonatomic) _Bool hasContentToDisplay;
@property(readonly, copy, nonatomic) NSString *messageCountText;
- (id)navigationBarText;
- (void)performTableViewDestructiveActionAtIndexPath:(id)arg1;
- (void)performTableViewRestoreActionAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)viewDidLoad;
- (void)willShowVoicemails:(id)arg1;

@end

