//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError;

@protocol PHVoicemailGreetingModelDelegate <NSObject>
- (void)voicemailGreetingAudioControllerDidChangeState:(long long)arg1;
- (void)voicemailGreetingDidFinishRecording;
- (void)voicemailGreetingDidSave;
- (void)voicemailGreetingDurationChanged:(double)arg1;
- (void)voicemailGreetingFailedWithError:(NSError *)arg1;
- (void)voicemailGreetingPlayingProgressChanged:(double)arg1;
- (void)voicemailGreetingRecordingProgressChanged:(double)arg1;
@end

