//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhoneNavigationController.h"

#import "VMPlayerControllerDelegate.h"
#import "VMSetupViewControllerDelegate.h"

@class MPVoicemailController, MPVoicemailTableViewController<PHVoicemailListProtocol>, NSString, PHVoicemailNoContentViewController, UIAlertController, VMCallVoicemailViewController, VMPlayerController, VMSetupViewController;

@interface PHVoicemailNavigationController : PhoneNavigationController <VMPlayerControllerDelegate, VMSetupViewControllerDelegate>
{
    _Bool _mailboxRequiresSetupPreviousValue;
    _Bool _sharedServiceIsSubscribedPreviousValue;
    _Bool _active;
    MPVoicemailTableViewController<PHVoicemailListProtocol> *_inboxViewController;
    MPVoicemailTableViewController<PHVoicemailListProtocol> *_trashViewController;
    MPVoicemailTableViewController<PHVoicemailListProtocol> *_blockedViewController;
    PHVoicemailNoContentViewController *_noContentViewController;
    VMPlayerController *_playerController;
    MPVoicemailController *_voicemailController;
    VMSetupViewController *_setupViewController;
    VMCallVoicemailViewController *_callVoicemailViewController;
    UIAlertController *_mailboxStorageAlertController;
}

+ (CDStruct_5ec447a9)badge;
+ (id)tabBarIconImage;
+ (id)tabBarIconImageName;
+ (id)tabBarIconName;
+ (int)tabViewType;
- (void).cxx_destruct;
- (void)_checkMailboxUsage;
- (void)_handleApplicationResumeNotification:(id)arg1;
- (void)_handleCTIndicatorsVoicemailNotification:(id)arg1;
- (void)_handleMessageWaitingStateChanged:(id)arg1;
- (void)_handleOnlineStateChanged:(id)arg1;
- (void)_handlePhoneActivationChangedNotification:(id)arg1;
- (void)_handleStorageUsageChangedNotification:(id)arg1;
- (void)_handleVoicemailSubscriptionStatusChangedNotification:(id)arg1;
- (void)_handleVoicemailsChangedNotification:(id)arg1;
- (void)_invalidateBadge;
- (void)_playVoicemailSound;
- (void)_updateUIState;
- (void)_updateUIStateForce:(_Bool)arg1;
@property(nonatomic) _Bool active; // @synthesize active=_active;
- (void)addNotificationObservers;
@property(readonly, nonatomic) MPVoicemailTableViewController<PHVoicemailListProtocol> *blockedViewController; // @synthesize blockedViewController=_blockedViewController;
@property(retain, nonatomic) VMCallVoicemailViewController *callVoicemailViewController; // @synthesize callVoicemailViewController=_callVoicemailViewController;
- (void)dealloc;
- (void)handleURL:(id)arg1;
@property(readonly, nonatomic) MPVoicemailTableViewController<PHVoicemailListProtocol> *inboxViewController; // @synthesize inboxViewController=_inboxViewController;
- (id)init;
@property(nonatomic) _Bool mailboxRequiresSetupPreviousValue; // @synthesize mailboxRequiresSetupPreviousValue=_mailboxRequiresSetupPreviousValue;
@property(retain, nonatomic) UIAlertController *mailboxStorageAlertController; // @synthesize mailboxStorageAlertController=_mailboxStorageAlertController;
@property(readonly, nonatomic) PHVoicemailNoContentViewController *noContentViewController; // @synthesize noContentViewController=_noContentViewController;
@property(retain, nonatomic) VMPlayerController *playerController; // @synthesize playerController=_playerController;
- (void)playerController:(id)arg1 didChangeToCurrentTime:(float)arg2;
- (void)playerController:(id)arg1 didChangeToDuration:(double)arg2;
- (void)playerController:(id)arg1 didChangeToStatus:(long long)arg2;
- (void)playerController:(id)arg1 didChangeToTimeControlStatus:(long long)arg2;
- (void)playerController:(id)arg1 didSeekToTime:(float)arg2;
- (void)playerControllerDidReset:(id)arg1;
- (id)popToRootViewControllerAnimated:(_Bool)arg1;
- (void)removeNotificationObservers;
- (id)selectedMessage;
- (id)selectedMessageTableViewCell;
@property(retain, nonatomic) VMSetupViewController *setupViewController; // @synthesize setupViewController=_setupViewController;
@property(nonatomic) _Bool sharedServiceIsSubscribedPreviousValue; // @synthesize sharedServiceIsSubscribedPreviousValue=_sharedServiceIsSubscribedPreviousValue;
@property(retain, nonatomic) MPVoicemailController *voicemailController; // @synthesize voicemailController=_voicemailController;
- (void)setupViewControllerDidFinish:(id)arg1;
- (_Bool)shouldSnapshot;
@property(readonly, nonatomic) MPVoicemailTableViewController<PHVoicemailListProtocol> *trashViewController; // @synthesize trashViewController=_trashViewController;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

