//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PHAudioRecorderDelegate.h"

@class PHAudioRecorder, VMVoicemailGreeting, VMVoicemailManager;

@interface PHVoicemailGreetingModel : NSObject <PHAudioRecorderDelegate>
{
    id <PHVoicemailGreetingModelDelegate> _delegate;
    long long _greetingState;
    VMVoicemailGreeting *_currentGreeting;
    double _maximumGreetingDuration;
    PHAudioRecorder *_greetingRecorder;
    double _greetingDuration;
}

- (void).cxx_destruct;
- (void)_handlePlayerControllerRateOrStatusChange:(id)arg1;
- (void)_handlePlayerDidFinishPlaying:(id)arg1;
- (void)_loadGreeting:(id)arg1;
- (void)_mediaserverReset:(id)arg1;
- (void)audioRecorderContinuedWithFile:(id)arg1 duration:(double)arg2;
- (void)audioRecorderEndedWithFile:(id)arg1 duration:(double)arg2 error:(id)arg3;
- (void)audioRecorderStartedWithFile:(id)arg1;
@property(retain, nonatomic) VMVoicemailGreeting *currentGreeting; // @synthesize currentGreeting=_currentGreeting;
- (void)dealloc;
@property(nonatomic) __weak id <PHVoicemailGreetingModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fetchGreeting;
@property(nonatomic) double greetingDuration; // @synthesize greetingDuration=_greetingDuration;
- (_Bool)greetingExists;
@property(retain, nonatomic) PHAudioRecorder *greetingRecorder; // @synthesize greetingRecorder=_greetingRecorder;
@property(nonatomic) long long greetingState; // @synthesize greetingState=_greetingState;
- (id)greetingTempFileLocation;
- (id)init;
- (long long)mailboxGreetingState;
@property(nonatomic) double maximumGreetingDuration; // @synthesize maximumGreetingDuration=_maximumGreetingDuration;
- (void)pauseGreeting;
- (void)playGreeting;
- (void)saveGreeting:(unsigned long long)arg1;
- (void)startRecording;
- (void)stopRecording;
@property(readonly, nonatomic) VMVoicemailManager *voicemailManager;

@end

