//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAsset, AVPlayer, AVPlayerItem;

@interface PHVoicemailPlayerController : NSObject
{
    _Bool _isWaitingForProximitySensor;
    _Bool _interrupted;
    long long _status;
    id <NSObject> _didStart;
    id <NSObject> _didEnd;
    id <NSObject> _timeObserver;
    AVPlayer *_audioPlayer;
    AVPlayerItem *_playerItem;
    CDStruct_1b6d18a9 _duration;
}

+ (id)sharedPlayerController;
- (void).cxx_destruct;
- (id)_createAVPlayer;
- (void)_pause;
- (void)_play;
- (void)_proximityStateChanged:(id)arg1;
@property(retain, nonatomic) AVPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
- (_Bool)beginInterruption;
@property(readonly, nonatomic) AVAsset *currentAsset;
- (void)currentAssetDurationWithBlock:(CDUnknownBlockType)arg1;
- (CDStruct_1b6d18a9)currentTime;
- (void)dealloc;
@property(retain, nonatomic) id <NSObject> didEnd; // @synthesize didEnd=_didEnd;
@property(retain, nonatomic) id <NSObject> didStart; // @synthesize didStart=_didStart;
@property(nonatomic) CDStruct_1b6d18a9 duration; // @synthesize duration=_duration;
- (_Bool)endInterruption;
- (void)handleAudioSessionRouteChangeNotification:(id)arg1;
- (id)init;
@property(nonatomic) _Bool interrupted; // @synthesize interrupted=_interrupted;
- (_Bool)isAtEnd;
- (_Bool)isPlaying;
@property(nonatomic) _Bool isWaitingForProximitySensor; // @synthesize isWaitingForProximitySensor=_isWaitingForProximitySensor;
- (void)loadAudio:(id)arg1 withObserverForInterval:(CDStruct_1b6d18a9)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)pause;
- (void)play;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
- (void)resetAudioPlayer;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) id <NSObject> timeObserver; // @synthesize timeObserver=_timeObserver;
- (void)updateProximityMonitoring;

@end

