//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TUCall.h"

@interface TUCall (PHUIUtilities)
- (_Bool)disconnectedReasonRequiresCallBackUI;
- (_Bool)disconnectedReasonRequiresCallFailureUI;
- (_Bool)hasSendCustomMessageCapability;
- (_Bool)hasSendMessageCapability;
- (id)sendMessageIntentExtension;
- (_Bool)shouldPlayInCallSounds;
- (_Bool)supportsSendMessageIntent;
@end

