//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (PhoneKit)
+ (id)preferredBoldFontWithTextStyle:(id)arg1;
+ (id)preferredCaption1BoldFont;
+ (id)preferredCaption1Font;
+ (id)preferredFontWithTextStyle:(id)arg1;
+ (id)preferredItalicFontWithTextStyle:(id)arg1;
+ (id)preferredSubheadline1Font;
+ (id)preferredTightLeadingWithForTextStyle:(id)arg1;
@end

