//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (MobilePhoneAdditions)
+ (id)_phImageNamed:(id)arg1 inBundle:(id)arg2 compatibleWithTraitCollection:(id)arg3;
+ (id)phCarPlayImageNamed:(id)arg1;
+ (id)phCarPlayImageNamed:(id)arg1 inBundle:(id)arg2;
+ (id)phImageNamed:(id)arg1;
+ (id)phPathForImageNamed:(id)arg1;
+ (id)phPathForImageNamed:(id)arg1 inBundle:(id)arg2;
@end

