//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPView.h"

@class NSLayoutConstraint, TPActionButton, UIButton;

@interface VMActivityButtonsView : TPView
{
    id <VMActivityButtonsViewDelegate> _delegate;
    TPActionButton *_actionButton;
    UIButton *_infoButton;
    NSLayoutConstraint *_actionButtonBottomLayoutConstraint;
    NSLayoutConstraint *_actionButtonCenterYLayoutConstraint;
    NSLayoutConstraint *_actionButtonLeadingLayoutConstraint;
    NSLayoutConstraint *_actionButtonTopLayoutConstraint;
    NSLayoutConstraint *_actionButtonTrailingLayoutConstraint;
    NSLayoutConstraint *_infoButtonBottomLayoutConstraint;
    NSLayoutConstraint *_infoButtonCenterYLayoutConstraint;
    NSLayoutConstraint *_infoButtonLeadingLayoutConstraint;
    NSLayoutConstraint *_infoButtonTopLayoutConstraint;
    NSLayoutConstraint *_infoButtonTrailingLayoutConstraint;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) TPActionButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) NSLayoutConstraint *actionButtonBottomLayoutConstraint; // @synthesize actionButtonBottomLayoutConstraint=_actionButtonBottomLayoutConstraint;
@property(readonly, nonatomic) double actionButtonBottomLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *actionButtonCenterYLayoutConstraint; // @synthesize actionButtonCenterYLayoutConstraint=_actionButtonCenterYLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *actionButtonLeadingLayoutConstraint; // @synthesize actionButtonLeadingLayoutConstraint=_actionButtonLeadingLayoutConstraint;
@property(readonly, nonatomic) double actionButtonLeadingLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *actionButtonTopLayoutConstraint; // @synthesize actionButtonTopLayoutConstraint=_actionButtonTopLayoutConstraint;
@property(readonly, nonatomic) double actionButtonTopLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *actionButtonTrailingLayoutConstraint; // @synthesize actionButtonTrailingLayoutConstraint=_actionButtonTrailingLayoutConstraint;
@property(readonly, nonatomic) double actionButtonTrailingLayoutConstraintConstant;
- (void)commonInit;
@property(nonatomic) __weak id <VMActivityButtonsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleActionForButtonSender:(id)arg1 event:(id)arg2;
@property(readonly, nonatomic) UIButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) NSLayoutConstraint *infoButtonBottomLayoutConstraint; // @synthesize infoButtonBottomLayoutConstraint=_infoButtonBottomLayoutConstraint;
@property(readonly, nonatomic) double infoButtonBottomLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *infoButtonCenterYLayoutConstraint; // @synthesize infoButtonCenterYLayoutConstraint=_infoButtonCenterYLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *infoButtonLeadingLayoutConstraint; // @synthesize infoButtonLeadingLayoutConstraint=_infoButtonLeadingLayoutConstraint;
@property(readonly, nonatomic) double infoButtonLeadingLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *infoButtonTopLayoutConstraint; // @synthesize infoButtonTopLayoutConstraint=_infoButtonTopLayoutConstraint;
@property(readonly, nonatomic) double infoButtonTopLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *infoButtonTrailingLayoutConstraint; // @synthesize infoButtonTrailingLayoutConstraint=_infoButtonTrailingLayoutConstraint;
@property(readonly, nonatomic) double infoButtonTrailingLayoutConstraintConstant;
- (id)initWithCoder:(id)arg1;
- (void)loadConstraints;
- (void)loadView;
- (void)setButtonType:(unsigned long long)arg1 enabled:(_Bool)arg2;
- (void)updateConstraintsConstants;

@end

