//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, _UIContentUnavailableView;

@interface VMContentUnavailableViewController : UIViewController
{
    unsigned long long _contentUnavailableStyle;
    NSString *_contentUnavailableTitle;
    _UIContentUnavailableView *_contentUnavailableView;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long contentUnavailableStyle; // @synthesize contentUnavailableStyle=_contentUnavailableStyle;
@property(copy, nonatomic) NSString *contentUnavailableTitle; // @synthesize contentUnavailableTitle=_contentUnavailableTitle;
@property(retain, nonatomic) _UIContentUnavailableView *contentUnavailableView; // @synthesize contentUnavailableView=_contentUnavailableView;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(unsigned long long)arg1;
- (void)loadView;

@end

