//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSLayoutConstraint, NSString, VMMessageHeaderView, VMMessageTranscriptView, VMPlayerControlsView;

@interface VMMessageView : UIView
{
    _Bool _shouldDisplayTranscript;
    _Bool _showsPlayerControls;
    _Bool _subviewsLoaded;
    _Bool _subviewsLayoutConstraintsLoaded;
    NSArray *_playerControlsViewLayoutConstraints;
    VMPlayerControlsView *_playerControlsView;
    VMMessageTranscriptView *_transcriptView;
    VMMessageHeaderView *_headerView;
    UIView *_transcriptSeparatorView;
    NSLayoutConstraint *_playerControlsViewTopAnchorLayoutConstraint;
    NSLayoutConstraint *_playerControlsViewBottomAnchorLayoutConstraint;
    NSLayoutConstraint *_transcriptSeparatorViewTopAnchorLayoutConstraint;
}

+ (_Bool)requiresConstraintBasedLayout;
- (void).cxx_destruct;
- (void)commonInit;
@property(retain, nonatomic) VMMessageHeaderView *headerView; // @synthesize headerView=_headerView;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadSubviews;
- (void)loadSubviewsLayoutConstraints;
@property(copy, nonatomic) NSString *localizedDate;
@property(copy, nonatomic) NSString *localizedHeadline;
@property(copy, nonatomic) NSString *localizedSubheadline;
@property(retain, nonatomic) VMPlayerControlsView *playerControlsView; // @synthesize playerControlsView=_playerControlsView;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewBottomAnchorLayoutConstraint; // @synthesize playerControlsViewBottomAnchorLayoutConstraint=_playerControlsViewBottomAnchorLayoutConstraint;
@property(copy, nonatomic) NSArray *playerControlsViewLayoutConstraints; // @synthesize playerControlsViewLayoutConstraints=_playerControlsViewLayoutConstraints;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewTopAnchorLayoutConstraint; // @synthesize playerControlsViewTopAnchorLayoutConstraint=_playerControlsViewTopAnchorLayoutConstraint;
@property(readonly, nonatomic) double playerControlsViewTopAnchorLayoutConstraintConstant;
@property(nonatomic) _Bool shouldDisplayTranscript; // @synthesize shouldDisplayTranscript=_shouldDisplayTranscript;
@property(nonatomic) _Bool showsPlayerControls; // @synthesize showsPlayerControls=_showsPlayerControls;
- (void)setShowsPlayerControls:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) _Bool subviewsLayoutConstraintsLoaded; // @synthesize subviewsLayoutConstraintsLoaded=_subviewsLayoutConstraintsLoaded;
@property(nonatomic) _Bool subviewsLoaded; // @synthesize subviewsLoaded=_subviewsLoaded;
@property(retain, nonatomic) UIView *transcriptSeparatorView; // @synthesize transcriptSeparatorView=_transcriptSeparatorView;
@property(retain, nonatomic) NSLayoutConstraint *transcriptSeparatorViewTopAnchorLayoutConstraint; // @synthesize transcriptSeparatorViewTopAnchorLayoutConstraint=_transcriptSeparatorViewTopAnchorLayoutConstraint;
@property(retain, nonatomic) VMMessageTranscriptView *transcriptView; // @synthesize transcriptView=_transcriptView;
@property(readonly, nonatomic) double transcriptSeparatorViewTopAnchorLayoutConstraintConstant;
- (void)updateConstraints;
- (void)updateConstraintsConstants;

@end

