//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, NSString, UILabel;

@interface VMMessageHeaderView : UIView
{
    _Bool _subviewsLoaded;
    _Bool _subviewsLayoutConstraintsLoaded;
    UILabel *_dateLabel;
    UILabel *_headlineLabel;
    UILabel *_subheadlineLabel;
    NSLayoutConstraint *_dateLabelFirstBaselineAnchorLayoutConstraint;
    NSLayoutConstraint *_headlineLabelFirstBaselineAnchorLayoutConstraint;
    NSLayoutConstraint *_subheadlineLabelFirstBaselineAnchorLayoutConstraint;
}

+ (_Bool)requiresConstraintBasedLayout;
- (void).cxx_destruct;
- (void)commonInit;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) NSLayoutConstraint *dateLabelFirstBaselineAnchorLayoutConstraint; // @synthesize dateLabelFirstBaselineAnchorLayoutConstraint=_dateLabelFirstBaselineAnchorLayoutConstraint;
@property(readonly, nonatomic) double dateLabelFirstBaselineAnchorLayoutConstraintConstant;
@property(retain, nonatomic) UILabel *headlineLabel; // @synthesize headlineLabel=_headlineLabel;
@property(retain, nonatomic) NSLayoutConstraint *headlineLabelFirstBaselineAnchorLayoutConstraint; // @synthesize headlineLabelFirstBaselineAnchorLayoutConstraint=_headlineLabelFirstBaselineAnchorLayoutConstraint;
@property(readonly, nonatomic) double headlineLabelFirstBaselineAnchorLayoutConstraintConstant;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadSubviews;
- (void)loadSubviewsLayoutConstraints;
@property(copy, nonatomic) NSString *localizedDate;
@property(copy, nonatomic) NSString *localizedHeadline;
@property(copy, nonatomic) NSString *localizedSubheadline;
@property(retain, nonatomic) UILabel *subheadlineLabel; // @synthesize subheadlineLabel=_subheadlineLabel;
@property(retain, nonatomic) NSLayoutConstraint *subheadlineLabelFirstBaselineAnchorLayoutConstraint; // @synthesize subheadlineLabelFirstBaselineAnchorLayoutConstraint=_subheadlineLabelFirstBaselineAnchorLayoutConstraint;
@property(nonatomic) _Bool subviewsLayoutConstraintsLoaded; // @synthesize subviewsLayoutConstraintsLoaded=_subviewsLayoutConstraintsLoaded;
@property(nonatomic) _Bool subviewsLoaded; // @synthesize subviewsLoaded=_subviewsLoaded;
@property(readonly, nonatomic) double subheadlineLabelFirstBaselineAnchorLayoutConstraintConstant;
- (void)updateConstraints;
- (void)updateConstraintsConstants;

@end

