//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSString;

@interface VMMessageTranscriptViewModel : NSObject
{
    _Bool _donated;
    _Bool _transcribing;
    _Bool _transcriptionAttempted;
    _Bool _transcriptionAvailable;
    float _messageTranscriptConfidence;
    unsigned long long _messageTranscriptConfidenceRating;
    NSString *_messageTranscriptAttributedText;
}

+ (id)negativeFeedbackURL;
+ (id)neutralFeedbackURL;
+ (id)positiveFeedbackURL;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long confidence;
@property(readonly, nonatomic) _Bool donated; // @synthesize donated=_donated;
- (id)initWithMessage:(id)arg1;
@property(nonatomic, getter=isTranscribing) _Bool transcribing; // @synthesize transcribing=_transcribing;
@property(nonatomic, getter=isTranscriptionAvailable) _Bool transcriptionAvailable; // @synthesize transcriptionAvailable=_transcriptionAvailable;
@property(readonly, copy, nonatomic) NSAttributedString *localizedAttributedFeedbackText;
- (id)localizedAttributedFeedbackTextForConfidence:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSAttributedString *localizedAttributedText;
- (id)localizedAttributedTextForConfidence:(unsigned long long)arg1;
- (id)localizedAttributedTextForMessage;
@property(readonly, copy, nonatomic) NSAttributedString *localizedAttributedTitle;
- (id)localizedAttributedTitleForConfidence:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSString *messageTranscriptAttributedText; // @synthesize messageTranscriptAttributedText=_messageTranscriptAttributedText;
@property(readonly, nonatomic) float messageTranscriptConfidence; // @synthesize messageTranscriptConfidence=_messageTranscriptConfidence;
@property(readonly, nonatomic) unsigned long long messageTranscriptConfidenceRating; // @synthesize messageTranscriptConfidenceRating=_messageTranscriptConfidenceRating;
@property(nonatomic) _Bool transcriptionAttempted; // @synthesize transcriptionAttempted=_transcriptionAttempted;

@end

