//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPView.h"

@class NSLayoutConstraint, UIButton, VMPlayerTimelineSlider;

@interface VMPlayerControlsView : TPView
{
    _Bool _enabled;
    id <VMPlayerControlsDelegate> _delegate;
    long long _state;
    UIButton *_playPauseButton;
    VMPlayerTimelineSlider *_timelineSlider;
    NSLayoutConstraint *_playPauseButtonBottomAnchorLayoutConstraint;
    NSLayoutConstraint *_playPauseButtonCenterYAnchorLayoutConstraint;
    NSLayoutConstraint *_playPauseButtonHeightAnchorLayoutConstraint;
    NSLayoutConstraint *_playPauseButtonLeadingAnchorLayoutConstraint;
    NSLayoutConstraint *_playPauseButtonTopAnchorLayoutConstraint;
    NSLayoutConstraint *_playPauseButtonTrailingAnchorLayoutConstraint;
    NSLayoutConstraint *_playPauseButtonWidthAnchorLayoutConstraint;
    NSLayoutConstraint *_timelineSliderBottomAnchorLayoutConstraint;
    NSLayoutConstraint *_timelineSliderLeadingAnchorLayoutConstraint;
    NSLayoutConstraint *_timelineSliderTopAnchorLayoutConstraint;
    NSLayoutConstraint *_timelineSliderTrailingAnchorLayoutConstraint;
}

- (void).cxx_destruct;
- (void)commonInit;
@property(nonatomic) __weak id <VMPlayerControlsDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double duration;
@property(nonatomic) double elapsedTime;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (void)loadConstraints;
- (void)loadSubviews;
@property(retain, nonatomic) UIButton *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(retain, nonatomic) NSLayoutConstraint *playPauseButtonBottomAnchorLayoutConstraint; // @synthesize playPauseButtonBottomAnchorLayoutConstraint=_playPauseButtonBottomAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playPauseButtonCenterYAnchorLayoutConstraint; // @synthesize playPauseButtonCenterYAnchorLayoutConstraint=_playPauseButtonCenterYAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playPauseButtonHeightAnchorLayoutConstraint; // @synthesize playPauseButtonHeightAnchorLayoutConstraint=_playPauseButtonHeightAnchorLayoutConstraint;
@property(readonly, nonatomic) double playPauseButtonHeightAnchorLayoutConstraintConstant;
@property(readonly, nonatomic) double playPauseButtonLeadingAnchorConstraintAccessibilityConstant;
@property(retain, nonatomic) NSLayoutConstraint *playPauseButtonLeadingAnchorLayoutConstraint; // @synthesize playPauseButtonLeadingAnchorLayoutConstraint=_playPauseButtonLeadingAnchorLayoutConstraint;
- (void)playPauseButtonTapped:(id)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) NSLayoutConstraint *playPauseButtonTopAnchorLayoutConstraint; // @synthesize playPauseButtonTopAnchorLayoutConstraint=_playPauseButtonTopAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playPauseButtonTrailingAnchorLayoutConstraint; // @synthesize playPauseButtonTrailingAnchorLayoutConstraint=_playPauseButtonTrailingAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playPauseButtonWidthAnchorLayoutConstraint; // @synthesize playPauseButtonWidthAnchorLayoutConstraint=_playPauseButtonWidthAnchorLayoutConstraint;
@property(readonly, nonatomic) double playPauseButtonWidthAnchorLayoutConstraintConstant;
- (void)setElapsedTime:(double)arg1 animated:(_Bool)arg2;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void)setState:(long long)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) VMPlayerTimelineSlider *timelineSlider; // @synthesize timelineSlider=_timelineSlider;
@property(retain, nonatomic) NSLayoutConstraint *timelineSliderBottomAnchorLayoutConstraint; // @synthesize timelineSliderBottomAnchorLayoutConstraint=_timelineSliderBottomAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *timelineSliderLeadingAnchorLayoutConstraint; // @synthesize timelineSliderLeadingAnchorLayoutConstraint=_timelineSliderLeadingAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *timelineSliderTopAnchorLayoutConstraint; // @synthesize timelineSliderTopAnchorLayoutConstraint=_timelineSliderTopAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *timelineSliderTrailingAnchorLayoutConstraint; // @synthesize timelineSliderTrailingAnchorLayoutConstraint=_timelineSliderTrailingAnchorLayoutConstraint;
@property(readonly, nonatomic) double timelineSliderLeadingAnchorConstraintAccessibilityConstant;
@property(readonly, nonatomic) double timelineSliderTopAnchorConstraintAccessibilityConstant;
- (void)transitionToState:(long long)arg1 animated:(_Bool)arg2;
- (void)updateConstraintsConstants;

@end

