//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPView.h"

#import "VMDetailSliderDelegate.h"

@class AVTimeFormatter, NSLayoutConstraint, NSString, UILabel, VMDetailSlider;

@interface VMPlayerTimelineSlider : TPView <VMDetailSliderDelegate>
{
    _Bool _labelsEnabled;
    id <VMPlayerTimelineSliderDelegate> _delegate;
    UILabel *_elapsedTimeLabel;
    UILabel *_remainingTimeLabel;
    VMDetailSlider *_slider;
    AVTimeFormatter *_timeFormatter;
    NSLayoutConstraint *_sliderBottomAnchorLayoutConstraint;
    NSLayoutConstraint *_sliderLeadingAnchorLayoutConstraint;
    NSLayoutConstraint *_sliderTopAnchorLayoutConstraint;
    NSLayoutConstraint *_sliderTrailingAnchorLayoutConstraint;
    NSLayoutConstraint *_elapsedTimeLabelBottomAnchorLayoutConstraint;
    NSLayoutConstraint *_elapsedTimeLabelLeadingAnchorLayoutConstraint;
    NSLayoutConstraint *_elapsedTimeLabelFirstBaselineAnchorLayoutConstraint;
    NSLayoutConstraint *_elapsedTimeLabelTrailingAnchorLayoutConstraint;
    NSLayoutConstraint *_remainingTimeLabelBottomAnchorLayoutConstraint;
    NSLayoutConstraint *_remainingTimeLabelLeadingAnchorLayoutConstraint;
    NSLayoutConstraint *_remainingTimeLabelFirstBaselineAnchorLayoutConstraint;
    NSLayoutConstraint *_remainingTimeLabelTrailingAnchorLayoutConstraint;
}

- (void).cxx_destruct;
- (void)commonInit;
@property(nonatomic) __weak id <VMPlayerTimelineSliderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)detailSlider:(id)arg1 didChangeElapsedTime:(double)arg2;
- (void)detailSliderTrackingDidBegin:(id)arg1;
- (void)detailSliderTrackingDidCancel:(id)arg1;
- (void)detailSliderTrackingDidEnd:(id)arg1;
@property(nonatomic) double duration;
@property(nonatomic) double elapsedTime;
@property(readonly, nonatomic) UILabel *elapsedTimeLabel; // @synthesize elapsedTimeLabel=_elapsedTimeLabel;
@property(retain, nonatomic) NSLayoutConstraint *elapsedTimeLabelBottomAnchorLayoutConstraint; // @synthesize elapsedTimeLabelBottomAnchorLayoutConstraint=_elapsedTimeLabelBottomAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *elapsedTimeLabelFirstBaselineAnchorLayoutConstraint; // @synthesize elapsedTimeLabelFirstBaselineAnchorLayoutConstraint=_elapsedTimeLabelFirstBaselineAnchorLayoutConstraint;
@property(readonly, nonatomic) double elapsedTimeLabelFirstBaselineAnchorLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *elapsedTimeLabelLeadingAnchorLayoutConstraint; // @synthesize elapsedTimeLabelLeadingAnchorLayoutConstraint=_elapsedTimeLabelLeadingAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *elapsedTimeLabelTrailingAnchorLayoutConstraint; // @synthesize elapsedTimeLabelTrailingAnchorLayoutConstraint=_elapsedTimeLabelTrailingAnchorLayoutConstraint;
@property(nonatomic) _Bool labelsEnabled; // @synthesize labelsEnabled=_labelsEnabled;
- (void)loadAccessibilityConstraints;
- (void)loadConstraints;
- (void)loadLabelConstraints;
- (void)loadView;
- (id)localizedStringForTimeInterval:(double)arg1 timeFormatter:(id)arg2;
@property(readonly, nonatomic) double remainingTime;
@property(readonly, nonatomic) UILabel *remainingTimeLabel; // @synthesize remainingTimeLabel=_remainingTimeLabel;
@property(retain, nonatomic) NSLayoutConstraint *remainingTimeLabelBottomAnchorLayoutConstraint; // @synthesize remainingTimeLabelBottomAnchorLayoutConstraint=_remainingTimeLabelBottomAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *remainingTimeLabelFirstBaselineAnchorLayoutConstraint; // @synthesize remainingTimeLabelFirstBaselineAnchorLayoutConstraint=_remainingTimeLabelFirstBaselineAnchorLayoutConstraint;
@property(readonly, nonatomic) double remainingTimeLabelFirstBaselineAnchorLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *remainingTimeLabelLeadingAnchorLayoutConstraint; // @synthesize remainingTimeLabelLeadingAnchorLayoutConstraint=_remainingTimeLabelLeadingAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *remainingTimeLabelTrailingAnchorLayoutConstraint; // @synthesize remainingTimeLabelTrailingAnchorLayoutConstraint=_remainingTimeLabelTrailingAnchorLayoutConstraint;
- (void)setElapsedTime:(double)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) NSLayoutConstraint *sliderBottomAnchorLayoutConstraint; // @synthesize sliderBottomAnchorLayoutConstraint=_sliderBottomAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *sliderLeadingAnchorLayoutConstraint; // @synthesize sliderLeadingAnchorLayoutConstraint=_sliderLeadingAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *sliderTopAnchorLayoutConstraint; // @synthesize sliderTopAnchorLayoutConstraint=_sliderTopAnchorLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *sliderTrailingAnchorLayoutConstraint; // @synthesize sliderTrailingAnchorLayoutConstraint=_sliderTrailingAnchorLayoutConstraint;
@property(retain, nonatomic) AVTimeFormatter *timeFormatter; // @synthesize timeFormatter=_timeFormatter;
- (void)setValue:(float)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) VMDetailSlider *slider; // @synthesize slider=_slider;
- (void)unloadConstraints;
- (void)updateConstraintsConstants;
- (void)updateElapsedTimeLabelText;
- (void)updateFonts;
- (void)updateRemainingTimeLabelText;
- (id)viewForFirstBaselineLayout;
- (id)viewForLastBaselineLayout;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

