//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMPlayerControllerDelegate.h"
#import "VMPlayerControlsDelegate.h"

@class VMPlayerController, VMPlayerControlsView;

@protocol VMPlayerViewController <VMPlayerControllerDelegate, VMPlayerControlsDelegate>
- (void)pause;
- (void)play;
@property(readonly, nonatomic) VMPlayerController *playerController;
@property(readonly, nonatomic) VMPlayerControlsView *playerControlsView;
- (void)stop;
@end

